import sys

def fix_file():
    path = r'c:\Users\Feedloop\OneDrive\Desktop\Demo File\remix-of-case-investigation-hub\src\pages\CaseWorkspacePage.tsx'
    with open(path, 'r', encoding='utf-8') as f:
        lines = f.readlines()

    # 1. Remove actor from initialAgentsState (Lines 443-465)
    # We'll just delete the block and update peepo's dependency
    del lines[442:465] # 443 to 465 (0-indexed 442 to 465)
    
    # 2. Update peepo's dependency (Now at a new line)
    for i in range(440, 460):
        if 'id: \'peepo\'' in lines[i]:
            for j in range(i, i+10):
                if 'dependencies: [\'actor\']' in lines[j]:
                    lines[j] = lines[j].replace('\'actor\'', '\'fact\'')
                    break
            break

    # 3. Remove 'actor' from startFullChain queue
    for i in range(3900, 4000):
        if 'setChainQueue(["fact", "actor", "peepo", "ipls", "prev"]);' in lines[i]:
            lines[i] = lines[i].replace('"actor", ', '')
            break

    # 4. Replace AnalysisTab return
    start_marker = '  return ('
    end_marker = 'function ReportsTab()'
    
    start_idx = -1
    end_idx = -1
    
    for i in range(3900, 4100):
        if start_marker in lines[i] and '<div className="flex h-full bg-[#f0f2f4]' in lines[i+1]:
            start_idx = i
            break
            
    for i in range(len(lines)-1, 5000, -1):
        if end_marker in lines[i]:
            end_idx = i
            break
            
    if start_idx != -1 and end_idx != -1:
        new_return = [
            '  return (\n',
            '    <div className="flex h-full bg-[#f0f2f4] overflow-hidden animate-in fade-in duration-500">\n',
            '         {/* Orchestration Sidebar */}\n',
            '         <div className="w-[320px] border-r border-slate-200 bg-slate-50 flex flex-col shrink-0 z-20 shadow-[1px_0_4px_rgba(0,0,0,0.02)]">\n',
            '            <div className="h-12 border-b border-slate-200 flex items-center justify-between px-5 bg-white shrink-0">\n',
            '               <div className="flex items-center gap-2">\n',
            '                  <div className={`h-2 w-2 rounded-full ${globalStatus === \'running\' ? \'bg-amber-500 animate-pulse\' : \'bg-slate-300\'}`} />\n',
            '                  <span className="text-[10px] font-bold text-slate-500 uppercase tracking-widest">Orchestration</span>\n',
            '               </div>\n',
            '               {globalStatus === \'running\' && (\n',
            '                  <Button onClick={stopChain} variant="ghost" size="sm" className="h-7 px-2 text-[9px] font-bold text-rose-500 hover:bg-rose-50 border border-rose-100">\n',
            '                     <XCircle className="h-3 w-3 mr-1" /> Stop\n',
            '                  </Button>\n',
            '               )}\n',
            '            </div>\n',
            '\n',
            '            <div className="p-4 bg-white border-b border-slate-100">\n',
            '               <Button \n',
            '                  onClick={startFullChain}\n',
            '                  disabled={globalStatus === \'running\'}\n',
            '                  className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold text-[10px] uppercase tracking-wider h-10  border-none group"\n',
            '               >\n',
            '                  <Play className="h-3 w-3 mr-2 group-hover:translate-x-0.5 transition-transform" /> Execute Full Chain\n',
            '               </Button>\n',
            '            </div>\n',
            '\n',
            '            <div className="flex-1 overflow-y-auto custom-scrollbar relative">\n',
            '               <div className="absolute left-[39px] top-6 bottom-6 w-px bg-slate-200 z-0" />\n',
            '               <div className="p-4 space-y-4 relative z-10">\n',
            '                  {agents.map((agent) => (\n',
            '                     <div \n',
            '                        key={agent.id}\n',
            '                        onClick={() => setSelectedAgentId(agent.id)}\n',
            '                        className={`\n',
            '                           group relative flex flex-col p-5 rounded-sm border bg-white transition-all cursor-pointer overflow-hidden\n',
            '                           ${selectedAgentId === agent.id ? "border-slate-900 ring-1 ring-slate-900/5 -translate-y-0.5" : "border-slate-200 hover:border-slate-300"}\n',
            '                        `}\n',
            '                     >\n',
            '                        <div className="flex items-start justify-between mb-4">\n',
            '                           <div className={`h-12 w-12 rounded-sm border flex items-center justify-center transition-all ${selectedAgentId === agent.id ? "bg-slate-900 text-white border-slate-900 shadow-slate-900/20" : "bg-white text-slate-400 border-slate-100"}`}>\n',
            '                              <agent.icon className="h-5 w-5" />\n',
            '                           </div>\n',
            '                           <div className="flex flex-col items-end gap-2">\n',
            '                              <div className={`\n',
            '                                   px-2 py-0.5 rounded text-[8px] font-black uppercase tracking-widest border\n',
            '                                   ${agent.status === \'completed\' ? \'bg-emerald-50 text-emerald-700 border-emerald-100\' : \n',
            '                                     agent.status === \'running\' ? \'bg-blue-50 text-blue-700 border-blue-100 animate-pulse\' : \n',
            '                                     agent.status === \'stopped\' ? \'bg-rose-50 text-rose-700 border-rose-100\' : \n',
            '                                     \'bg-slate-50 text-slate-400 border-slate-100\'}\n',
            '                              `}>\n',
            '                                   {agent.status}\n',
            '                              </div>\n',
            '                              {agent.lastRunTimestamp && (\n',
            '                                 <span className="text-[8px] font-bold text-slate-300 uppercase tracking-tight">{agent.lastRunTimestamp}</span>\n',
            '                              )}\n',
            '                           </div>\n',
            '                        </div>\n',
            '\n',
            '                        <div className="space-y-1 mb-4">\n',
            '                           <h4 className={`text-[11px] font-black uppercase tracking-[0.15em] ${selectedAgentId === agent.id ? "text-slate-900" : "text-slate-500"}`}>{agent.name}</h4>\n',
            '                           <p className="text-[10px] font-medium text-slate-400 leading-snug line-clamp-2 opacity-80">{agent.purpose}</p>\n',
            '                        </div>\n',
            '\n',
            '                        <div className="flex gap-2 pt-2 border-t border-slate-50">\n',
            '                           {agent.status === \'running\' ? (\n',
            '                              <Button \n',
            '                                 onClick={(e) => { e.stopPropagation(); stopSingleAgent(agent.id); }}\n',
            '                                 variant="outline" \n',
            '                                 className="flex-1 h-10 bg-rose-50 hover:bg-rose-100 border-rose-100 text-rose-600 text-[10px] font-black uppercase tracking-[0.1em] rounded-sm transition-all"\n',
            '                              >\n',
            '                                 <XCircle className="h-4 w-4 mr-2" /> Stop Node\n',
            '                              </Button>\n',
            '                           ) : (\n',
            '                              <>\n',
            '                                 <Button \n',
            '                                    onClick={(e) => { e.stopPropagation(); setPreRunAgentId(agent.id); }}\n',
            '                                    className="flex-1 h-10 bg-slate-900 hover:bg-slate-800 text-white text-[10px] font-black uppercase tracking-[0.1em] rounded-sm shadow-sm transition-all"\n',
            '                                 >\n',
            '                                    <Play className="h-3.5 w-3.5 mr-2 fill-current" /> {agent.runCount > 0 ? "Rerun" : "Execute"}\n',
            '                                 </Button>\n',
            '                                 <Button \n',
            '                                    variant="outline" \n',
            '                                    onClick={(e) => { e.stopPropagation(); setHistoryAgentId(agent.id); }}\n',
            '                                    className="h-10 w-10 bg-white border-slate-200 text-slate-500 text-[10px] font-black uppercase rounded-sm hover:bg-slate-50 transition-colors shrink-0"\n',
            '                                 >\n',
            '                                    <History className="h-4 w-4" />\n',
            '                                 </Button>\n',
            '                                 <Button \n',
            '                                    variant="outline" \n',
            '                                    className="h-10 w-10 bg-white border-slate-200 text-slate-500 text-[10px] font-black uppercase rounded-sm hover:bg-slate-50 transition-colors shrink-0"\n',
            '                                 >\n',
            '                                    <Settings className="h-4 w-4" />\n',
            '                                 </Button>\n',
            '                              </>\n',
            '                           )}\n',
            '                        </div>\n',
            '\n',
            '                        {agent.status === \'running\' && (\n',
            '                           <div className="absolute bottom-0 left-0 right-0 h-1 bg-slate-100 overflow-hidden">\n',
            '                              <div className="h-full bg-blue-500 animate-pulse w-full origin-left" />\n',
            '                           </div>\n',
            '                        )}\n',
            '                     </div>\n',
            '                  ))}\n',
            '               </div>\n',
            '            </div>\n',
            '         </div>\n',
            '\n',
            '         <div className="flex-1 flex flex-col min-w-0 bg-white">\n',
            '            <div className="flex-1 flex overflow-hidden">\n',
            '               <div ref={containerRef} className="flex-1 relative overflow-auto custom-scrollbar flex items-start justify-center">\n',
            '                  {selectedAgentId ? (\n',
            '                     <div className="bg-white flex-1 flex flex-col relative transition-all duration-300 origin-center overflow-hidden w-full h-full">\n',
            '                        <div className="flex-1 flex flex-col relative overflow-hidden h-full">\n',
            '                           {selectedAgent?.status === \'running\' ? (\n',
            '                              <div className="flex flex-col items-center justify-center h-full text-center space-y-8 animate-pulse text-slate-300">\n',
            '                                 <Loader2 className="h-12 w-12 animate-spin" />\n',
            '                                 <span className="text-[20px] font-black uppercase tracking-[0.2em]">{selectedAgent.microStatus || "Processing Matrix..."}</span>\n',
            '                              </div>\n',
            '                           ) : !selectedAgent?.results ? (\n',
            '                              <div className="flex flex-col h-full items-center justify-center text-center opacity-30 grayscale pointer-events-none space-y-6">\n',
            '                                 <Cpu className="h-12 w-12 text-slate-300" />\n',
            '                                 <h2 className="text-3xl font-black uppercase tracking-[0.2em] text-slate-400">Node Standby</h2>\n',
            '                              </div>\n',
            '                           ) : (\n',
            '                              <div className="flex-1 animate-in fade-in duration-500 overflow-hidden">\n',
            '                                 {slides[activeSlide]?.type === \'chronology_module\' ? (\n',
            '                                    <FactChronologyModule \n',
            '                                       initialItems={slides[activeSlide]?.content?.items || []}\n',
            '                                       metadata={slides[activeSlide]?.content?.metadata}\n',
            '                                       viewMode={factViewMode}\n',
            '                                       onViewModeChange={setFactViewMode}\n',
            '                                       selectedItemId={selectedRowId || undefined}\n',
            '                                       onSelectItem={handleSelectRow}\n',
            '                                       onSync={(newItems) => {\n',
            '                                          setAgents(prev => prev.map(a => a.id === \'fact\' ? {\n',
            '                                             ...a,\n',
            '                                             results: { ...a.results, chronology_items: newItems }\n',
            '                                          } : a));\n',
            '                                          toast.success("Chronology successfully synced to case intelligence.");\n',
            '                                       }}\n',
            '                                    />\n',
            '                                 ) : (\n',
            '                                    <div className="flex flex-col h-full p-8">\n',
            '                                       <h2 className="text-[32px] font-black text-slate-800 mb-8 tracking-tighter uppercase">{slides[activeSlide]?.title}</h2>\n',
            '                                       {selectedAgentId === \'peepo\' ? (\n',
            '                                          <div className="flex flex-col h-full bg-slate-50/10 animate-in fade-in duration-500 overflow-hidden">\n',
            '                                             <div className="h-12 flex items-center justify-between px-5 border-b border-slate-200 bg-white shrink-0">\n',
            '                                                <div className="flex items-center gap-2">\n',
            '                                                   <div className="h-2 w-2 rounded-full bg-[#8ba861]" />\n',
            '                                                   <h2 className="text-[10px] font-black text-slate-900 uppercase tracking-widest">PEEPO Factor Analysis Sheet</h2>\n',
            '                                                </div>\n',
            '                                                <div className="flex items-center gap-2">\n',
            '                                                   <div className="h-2 w-2 bg-emerald-500 rounded-full animate-pulse" />\n',
            '                                                   <span className="text-[9px] font-bold text-slate-400 uppercase tracking-tight">Synthesis Complete</span>\n',
            '                                                </div>\n',
            '                                             </div>\n',
            '                                             <div className="flex-1 overflow-auto p-6 scrollbar-thin">\n',
            '                                                <div className="max-w-5xl mx-auto space-y-8 pb-12">\n',
            '                                                   {[\n',
            '                                                      { id: \'people\', label: \'People (Individu)\' },\n',
            '                                                      { id: \'environment\', label: \'Environment (Lingkungan)\' },\n',
            '                                                      { id: \'equipment\', label: \'Equipment (Peralatan)\' },\n',
            '                                                      { id: \'procedures\', label: \'Procedures (Prosedur)\' },\n',
            '                                                      { id: \'organisation\', label: \'Organisation (Organisasi)\' },\n',
            '                                                   ].map((section) => (\n',
            '                                                      <div key={section.id} className="space-y-3">\n',
            '                                                         <div className="flex items-center gap-3">\n',
            '                                                            <span className="px-2.5 py-1 rounded text-[9px] font-black text-white uppercase tracking-widest bg-slate-900">\n',
            '                                                               {section.label}\n',
            '                                                            </span>\n',
            '                                                            <div className="h-px flex-1 bg-slate-200" />\n',
            '                                                         </div>\n',
            '                                                         <div className="bg-white border-l border-t border-slate-200 overflow-hidden shadow-sm">\n',
            '                                                            <table className="w-full text-left border-collapse">\n',
            '                                                               <thead>\n',
            '                                                                  <tr className="bg-slate-50/80">\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-24 border-r border-b border-slate-200 bg-slate-50/30">ID</th>\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest border-r border-b border-slate-200 bg-slate-50/30">Forensic Finding</th>\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-32 border-r border-b border-slate-200 bg-slate-50/30">Traceability</th>\n',
            '                                                                  </tr>\n',
            '                                                               </thead>\n',
            '                                                               <tbody>\n',
            '                                                                  {(selectedAgent?.results?.[section.id] || []).map((item: any, idx: number) => {\n',
            '                                                                     const isSelected = selectedRowId === (item.id || item);\n',
            '                                                                     return (\n',
            '                                                                        <tr \n',
            '                                                                           key={item.id || idx} \n',
            '                                                                           onClick={() => handleSelectRow(item.id || item)}\n',
            '                                                                           className={cn("group transition-all cursor-pointer", isSelected ? "bg-slate-100/80" : "hover:bg-slate-50/50")}\n',
            '                                                                        >\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200">\n',
            '                                                                              <span className="text-[11px] font-mono font-black text-slate-400">#{section.id.slice(0, 1).toUpperCase()}{idx + 1}</span>\n',
            '                                                                           </td>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200">\n',
            '                                                                              <p className={cn("text-[11px] font-bold leading-relaxed pr-8", isSelected ? "text-slate-900" : "text-slate-700")}>\n',
            '                                                                                 {item.label || item}\n',
            '                                                                              </p>\n',
            '                                                                           </td>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200 text-center">\n',
            '                                                                              <Search className={cn("h-3.5 w-3.5 mx-auto", isSelected ? "text-slate-900" : "text-slate-300")} />\n',
            '                                                                           </td>\n',
            '                                                                        </tr>\n',
            '                                                                     );\n',
            '                                                                  })}\n',
            '                                                               </tbody>\n',
            '                                                            </table>\n',
            '                                                         </div>\n',
            '                                                      </div>\n',
            '                                                   ))}\n',
            '                                                   <div className="grid grid-cols-2 gap-6 pt-4">\n',
            '                                                      <div className="bg-white border-l border-t border-slate-200 p-6 shadow-sm rounded-sm">\n',
            '                                                         <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-2">Analysis Summary</span>\n',
            '                                                         <p className="text-[11px] font-bold text-slate-600 leading-relaxed italic">"{selectedAgent?.results?.ringkasan}"</p>\n',
            '                                                      </div>\n',
            '                                                      <div className="bg-slate-900 p-6 shadow-sm border border-slate-800 rounded-sm">\n',
            '                                                         <span className="text-[9px] font-black text-emerald-400/50 uppercase tracking-widest block mb-2">Synthesis Intelligence</span>\n',
            '                                                         <p className="text-[11px] font-black text-white uppercase tracking-tight leading-relaxed">{selectedAgent?.results?.synthesis}</p>\n',
            '                                                      </div>\n',
            '                                                   </div>\n',
            '                                                </div>\n',
            '                                             </div>\n',
            '                                          </div>\n',
            '                                       ) : selectedAgentId === \'ipls\' ? (\n',
            '                                          <div className="flex flex-col h-full bg-slate-50/10 animate-in fade-in duration-500 overflow-hidden">\n',
            '                                             <div className="h-12 flex items-center justify-between px-5 border-b border-slate-200 bg-white shrink-0">\n',
            '                                                <div className="flex items-center gap-2">\n',
            '                                                   <div className="h-2 w-2 rounded-full bg-[#8ba861]" />\n',
            '                                                   <h2 className="text-[10px] font-black text-slate-900 uppercase tracking-widest">Integrated Profile Layer (IPLS) Sheet</h2>\n',
            '                                                </div>\n',
            '                                                <div className="flex items-center gap-2">\n',
            '                                                   <div className="h-2 w-2 bg-emerald-500 rounded-full animate-pulse" />\n',
            '                                                   <span className="text-[9px] font-bold text-slate-400 uppercase tracking-tight">Defensive Audit Complete</span>\n',
            '                                                </div>\n',
            '                                             </div>\n',
            '                                             <div className="flex-1 overflow-auto p-6 scrollbar-thin">\n',
            '                                                <div className="max-w-[1400px] mx-auto space-y-8 pb-12">\n',
            '                                                   {(selectedAgent?.results?.layers || []).map((layer: any) => (\n',
            '                                                      <div key={layer.id} className="space-y-3">\n',
            '                                                         <div className="flex items-center gap-3">\n',
            '                                                            <span className="px-2.5 py-1 rounded text-[9px] font-black text-white uppercase tracking-widest bg-slate-900">\n',
            '                                                               Layer {["I", "II", "III", "IV", "V"][layer.id - 1]}: {layer.title}\n',
            '                                                            </span>\n',
            '                                                            <div className="h-px flex-1 bg-slate-200" />\n',
            '                                                         </div>\n',
            '                                                         <div className="bg-white border-l border-t border-slate-200 overflow-hidden shadow-sm">\n',
            '                                                            <table className="w-full text-left border-collapse">\n',
            '                                                               <thead>\n',
            '                                                                  <tr className="bg-slate-50/80">\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-24 border-r border-b border-slate-200 bg-slate-50/30">STATUS</th>\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest border-r border-b border-slate-200 bg-slate-50/30">Defensive Audit Point</th>\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-32 border-r border-b border-slate-200 bg-slate-50/30">Traceability</th>\n',
            '                                                                  </tr>\n',
            '                                                               </thead>\n',
            '                                                               <tbody>\n',
            '                                                                  {layer.items.map((item: any, idx: number) => {\n',
            '                                                                     const isSelected = selectedRowId === item.id;\n',
            '                                                                     return (\n',
            '                                                                        <tr key={item.id || idx} onClick={() => handleSelectRow(item.id)} className={cn("group transition-all cursor-pointer", isSelected ? "bg-slate-100/80" : "hover:bg-slate-50/50")}>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200">\n',
            '                                                                              <div className="flex justify-center">\n',
            '                                                                                 {item.status === \'rootcause\' ? (\n',
            '                                                                                    <div className="h-4 w-4 rounded-full border-2 border-red-500 flex items-center justify-center"><div className="h-1.5 w-1.5 rounded-full bg-red-500" /></div>\n',
            '                                                                                 ) : item.status === \'non-conformity\' ? (\n',
            '                                                                                    <div className="h-4 w-4 rounded-full border-2 border-amber-500 flex items-center justify-center"><div className="h-1.5 w-1.5 rounded-full bg-amber-500" /></div>\n',
            '                                                                                 ) : (\n',
            '                                                                                    <div className="h-4 w-4 rounded-full border-2 border-emerald-500 flex items-center justify-center"><div className="h-1.5 w-1.5 rounded-full bg-emerald-500" /></div>\n',
            '                                                                                 )}\n',
            '                                                                              </div>\n',
            '                                                                           </td>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200">\n',
            '                                                                              <p className={cn("text-[11px] font-bold leading-relaxed pr-8", isSelected ? "text-slate-900" : "text-slate-700")}>{item.label}</p>\n',
            '                                                                           </td>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200 text-center">\n',
            '                                                                              <Search className={cn("h-3.5 w-3.5 mx-auto", isSelected ? "text-slate-900" : "text-slate-300")} />\n',
            '                                                                           </td>\n',
            '                                                                        </tr>\n',
            '                                                                     );\n',
            '                                                                  })}\n',
            '                                                               </tbody>\n',
            '                                                            </table>\n',
            '                                                         </div>\n',
            '                                                      </div>\n',
            '                                                   ))}\n',
            '                                                </div>\n',
            '                                             </div>\n',
            '                                          </div>\n',
            '                                       ) : selectedAgentId === \'prev\' ? (\n',
            '                                          <div className="flex flex-col h-full bg-slate-50/10 animate-in fade-in duration-500 overflow-hidden">\n',
            '                                             <div className="h-12 flex items-center justify-between px-5 border-b border-slate-200 bg-white shrink-0">\n',
            '                                                <div className="flex items-center gap-2">\n',
            '                                                   <div className="h-2 w-2 rounded-full bg-[#8ba861]" />\n',
            '                                                   <h2 className="text-[10px] font-black text-slate-900 uppercase tracking-widest">Prevention Action Plan Sheet</h2>\n',
            '                                                </div>\n',
            '                                                <div className="flex items-center gap-2">\n',
            '                                                   <div className="h-2 w-2 bg-emerald-500 rounded-full animate-pulse" />\n',
            '                                                   <span className="text-[9px] font-bold text-slate-400 uppercase tracking-tight">Plan Finalized</span>\n',
            '                                                </div>\n',
            '                                             </div>\n',
            '                                             <div className="flex-1 overflow-auto p-6 scrollbar-thin">\n',
            '                                                <div className="max-w-[1600px] mx-auto space-y-10 pb-12">\n',
            '                                                   {[\n',
            '                                                      { id: \'root\', title: \'Root Cause Actions\', color: \'bg-red-500\', data: selectedAgent?.results?.root_cause_actions },\n',
            '                                                      { id: \'nc\', title: \'Non Conformity Actions\', color: \'bg-amber-500\', data: selectedAgent?.results?.non_conformity_actions },\n',
            '                                                      { id: \'imp\', title: \'Improvement Actions\', color: \'bg-emerald-500\', data: selectedAgent?.results?.improvement_actions },\n',
            '                                                   ].map((section) => (\n',
            '                                                      <div key={section.id} className="space-y-3">\n',
            '                                                         <div className="flex items-center gap-3">\n',
            '                                                            <span className={cn("px-2.5 py-1 rounded text-[9px] font-black text-white uppercase tracking-widest", section.color)}>{section.title}</span>\n',
            '                                                            <div className="h-px flex-1 bg-slate-200" />\n',
            '                                                         </div>\n',
            '                                                         <div className="bg-white border-l border-t border-slate-200 overflow-hidden shadow-sm">\n',
            '                                                            <table className="w-full text-left border-collapse">\n',
            '                                                               <thead>\n',
            '                                                                  <tr className="bg-slate-50/80">\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-12 border-r border-b border-slate-200 bg-slate-50/30">NO</th>\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-24 border-r border-b border-slate-200 bg-slate-50/30">LAYER</th>\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-32 border-r border-b border-slate-200 bg-slate-50/30">CONTROL</th>\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest border-r border-b border-slate-200 bg-slate-50/30">Prevention Action</th>\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-32 border-r border-b border-slate-200 bg-slate-50/30">PIC</th>\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-24 border-r border-b border-slate-200 bg-slate-50/30">DUE DATE</th>\n',
            '                                                                     <th className="px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-24 border-b border-slate-200 bg-slate-50/30 text-center">STATUS</th>\n',
            '                                                                  </tr>\n',
            '                                                               </thead>\n',
            '                                                               <tbody>\n',
            '                                                                  {(section.data || []).map((item: any, idx: number) => {\n',
            '                                                                     const isSelected = selectedRowId === item.id;\n',
            '                                                                     return (\n',
            '                                                                        <tr key={item.id || idx} onClick={() => handleSelectRow(item.id)} className={cn("group transition-all cursor-pointer", isSelected ? "bg-slate-100/80" : "hover:bg-slate-50/50")}>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200 text-center text-[11px] font-mono font-black text-slate-400">{item.no}</td>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200 text-center text-[10px] font-black text-slate-500 uppercase">{item.layer}</td>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200 text-center text-[10px] font-black text-slate-900 uppercase tracking-tighter">{item.hierarchy}</td>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200"><p className={cn("text-[11px] font-bold leading-relaxed pr-8 uppercase tracking-tight", isSelected ? "text-slate-900" : "text-slate-700")}>{item.action}</p></td>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200 text-center text-[10px] font-bold text-slate-600">{item.pic}</td>\n',
            '                                                                           <td className="px-5 py-4 align-top border-r border-b border-slate-200 text-center text-[10px] font-mono text-slate-500">{item.due_date}</td>\n',
            '                                                                           <td className="p-0 border-b border-slate-200"><div className={cn("h-12 flex items-center justify-center text-[9px] font-black tracking-widest uppercase", item.status === \'OPEN\' ? "bg-red-50 text-red-600" : item.status === \'PROGRESS\' ? "bg-amber-50 text-amber-600" : "bg-emerald-50 text-emerald-600")}>{item.status}</div></td>\n',
            '                                                                        </tr>\n',
            '                                                                     );\n',
            '                                                                  })}\n',
            '                                                               </tbody>\n',
            '                                                            </table>\n',
            '                                                         </div>\n',
            '                                                      </div>\n',
            '                                                   ))}\n',
            '                                                </div>\n',
            '                                             </div>\n',
            '                                          </div>\n',
            '                                       ) : (\n',
            '                                          <div className="flex-1 bg-[#1a1c23] rounded-sm p-6 overflow-hidden border border-slate-700 relative">\n',
            '                                             <pre className="text-[12px] font-mono text-emerald-400/90 leading-tight h-full overflow-auto custom-scrollbar">{JSON.stringify(slides[activeSlide]?.content, null, 2)}</pre>\n',
            '                                          </div>\n',
            '                                       )}\n',
            '                                    </div>\n',
            '                                 )}\n',
            '                              </div>\n',
            '                           )}\n',
            '                        </div>\n',
            '                     </div>\n',
            '                  ) : (\n',
            '                     <div className="flex-1 flex flex-col items-center justify-center p-12 text-slate-300">\n',
            '                        <Brain className="h-12 w-12 mb-4 opacity-20" />\n',
            '                        <h2 className="text-3xl font-black uppercase tracking-[0.2em] text-slate-400">Orchestration Idle</h2>\n',
            '                        <p className="text-[10px] mt-2 opacity-50 font-bold uppercase">Select a node to view intelligence results</p>\n',
            '                     </div>\n',
            '                  )}\n',
            '               </div>\n',
            '\n',
            '               {/* Right Sidebar: Evidence Console */}\n',
            '               <div className="w-[460px] border-l border-slate-200 bg-white flex flex-col shrink-0">\n',
            '                  {selectedRowId ? (\n',
            '                     (() => {\n',
            '                        const agent = agents.find(a => a.id === selectedAgentId);\n',
            '                        let item = agent?.results?.chronology_items?.find((i: any) => i.id === selectedRowId) || \n',
            '                                     agent?.results?.layers?.flatMap((l: any) => l.items).find((i: any) => i.id === selectedRowId) ||\n',
            '                                     agent?.results?.root_cause_actions?.find((i: any) => i.id === selectedRowId) ||\n',
            '                                     agent?.results?.non_conformity_actions?.find((i: any) => i.id === selectedRowId) ||\n',
            '                                     agent?.results?.improvement_actions?.find((i: any) => i.id === selectedRowId);\n',
            '                        \n',
            '                        if (!item && selectedRowId) {\n',
            '                           item = { id: selectedRowId, label: selectedRowId, timestamp: "Forensic Synthesis", status: "Verified", description: `Automatic trace synthesis for finding: "${selectedRowId}". Linked to Case CS-2026-0147.` };\n',
            '                        }\n',
            '                        \n',
            '                        if (!item) return <div className="flex-1 flex flex-col items-center justify-center p-12 text-slate-300"><Search className="h-12 w-12 mb-4 opacity-20" /><h4 className="text-[10px] font-black uppercase tracking-[0.2em]">Finding Not Resolved</h4></div>;\n',
            '\n',
            '                        return (\n',
            '                           <div className="flex flex-col h-full bg-white animate-in fade-in duration-300">\n',
            '                              <div className="h-12 border-b border-slate-200 flex items-center justify-between px-5 bg-slate-50/50 shrink-0">\n',
            '                                 <div className="flex items-center gap-2"><Brain className="h-4 w-4 text-primary" /><span className="text-[10px] font-black text-slate-700 uppercase tracking-widest">Evidence Console</span></div>\n',
            '                                 <div className="flex items-center gap-2"><Button variant="ghost" size="sm" onClick={() => setSelectedRowId(null)} className="h-8 w-8 p-0 text-slate-400 hover:text-slate-600 hover:bg-slate-100"><X className="h-4 w-4" /></Button></div>\n',
            '                              </div>\n',
            '                              <div className="flex-1 flex flex-col overflow-hidden bg-white">\n',
            '                                 <div className="px-5 py-4 border-b border-slate-100 bg-white shrink-0">\n',
            '                                    <div className="flex bg-slate-200 p-0.5 rounded-sm mb-4">\n',
            '                                       <button onClick={() => setActiveEvidenceConsoleMode(\'trace\')} className={cn("flex-1 py-1 text-[8px] font-black uppercase rounded-sm transition-all", activeEvidenceConsoleMode === \'trace\' ? "bg-white shadow-sm text-slate-900" : "text-slate-400")}>Trace</button>\n',
            '                                       <button onClick={() => setActiveEvidenceConsoleMode(\'diarization\')} className={cn("flex-1 py-1 text-[8px] font-black uppercase rounded-sm transition-all", activeEvidenceConsoleMode === \'diarization\' ? "bg-white shadow-sm text-slate-900" : "text-slate-400")}>Diarization</button>\n',
            '                                    </div>\n',
            '                                    <div className="space-y-1">\n',
            '                                       <button onClick={() => setExpandedFolders(prev => prev.includes(\'audio\') ? prev.filter(f => f !== \'audio\') : [...prev, \'audio\'])} className="w-full flex items-center justify-between p-2 rounded-sm group transition-colors"><div className="flex items-center gap-2"><Folders className="h-3.5 w-3.5 text-slate-400 group-hover:text-primary" /><span className="text-[10px] font-black uppercase tracking-widest text-slate-500">Audio Evidence</span></div>{expandedFolders.includes(\'audio\') ? <ChevronDown className="h-3 w-3 text-slate-300" /> : <ChevronRight className="h-3 w-3 text-slate-300" />}</button>\n',
            '                                       {expandedFolders.includes(\'audio\') && (<div className="ml-4 pl-2 border-l border-slate-100 space-y-0.5"><button onClick={() => setActiveEvidenceType(\'audio_diarization\')} className={cn("w-full flex items-center gap-2 p-2 rounded-sm text-[9px] font-black uppercase tracking-widest", activeEvidenceType === \'audio_diarization\' ? "bg-slate-900 text-white" : "text-slate-400")}>Diarization Session</button></div>)}\n',
            '                                    </div>\n',
            '                                 </div>\n',
            '                                 <div className="flex-1 overflow-y-auto custom-scrollbar p-6 bg-slate-50/20">\n',
            '                                    {activeEvidenceType === \'audio_diarization\' && (<div className="space-y-4">{audioEvidence.diarization.map((seg, idx) => (<div key={idx} className="border-l-2 border-slate-900 pl-4 py-1 bg-white p-3 rounded-sm border border-slate-100 shadow-sm mb-4"><div className="flex items-center gap-3 mb-2"><span className="text-[10px] font-mono font-black text-slate-400">{seg.startTime} — {seg.endTime}</span><span className="px-2 py-0.5 bg-slate-900 text-white text-[8px] font-black uppercase rounded-sm">{seg.speaker}</span></div><p className="text-xs font-medium leading-relaxed text-slate-700 italic">"{seg.text}"</p></div>))}</div>)}\n',
            '                                 </div>\n',
            '                              </div>\n',
            '                           </div>\n',
            '                        );\n',
            '                     })()\n',
            '                  ) : (\n',
            '                     <div className="flex-1 flex flex-col items-center justify-center p-12 text-slate-300"><Search className="h-12 w-12 mb-4 opacity-20" /><h4 className="text-[10px] font-black uppercase tracking-[0.2em]">Console Standby</h4></div>\n',
            '                  )}\n',
            '               </div>\n',
            '            </div>\n',
            '         </div>\n',
            '\n',
            '         {preRunAgentId && (<PreRunModal agent={agents.find(a => a.id === preRunAgentId)!} onClose={() => setPreRunAgentId(null)} onRun={(rerun) => runSingleAgent(preRunAgentId, rerun)} />)}\n',
            '         {historyAgentId && (<AgentHistoryPanel agent={agents.find(a => a.id === historyAgentId)!} onClose={() => setHistoryAgentId(null)} />)}\n',
            '      </div>\n',
            '    );\n'
        ]
        
        print(f"Replacing AnalysisTab return from line {start_idx+1} to {end_idx}")
        lines[start_idx:end_idx] = new_return

    with open(path, 'w', encoding='utf-8') as f:
        f.writelines(lines)

if __name__ == "__main__":
    fix_file()
