
import os

file_path = r"c:\Users\Feedloop\OneDrive\Desktop\Demo File\remix-of-case-investigation-hub\src\pages\CaseWorkspacePage.tsx"

with open(file_path, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Look for the start of the orchestration container
start_index = -1
for idx, line in enumerate(lines):
    if 'ref={containerRef}' in line:
        start_index = idx
        break

if start_index == -1:
    print("Could not find start index")
    exit(1)

# Look for the start of the right sidebar
end_index = -1
for idx, line in enumerate(lines):
    if 'Right Sidebar: Fact Trace Panel' in line:
        end_index = idx
        break

if end_index == -1:
    print("Could not find end index")
    exit(1)

# We will replace the entire content between start_index and end_index
# with a clean version of the orchestration logic.

new_orchestration = [
    lines[start_index], # <div ref={containerRef} ...>
    "                  {selectedAgentId ? (\n",
    "                     <div className=\"bg-white flex-1 flex flex-col relative transition-all duration-300 origin-center overflow-hidden w-full h-full\">\n",
    "                        <div className=\"flex-1 flex flex-col relative overflow-hidden h-full\">\n",
    "                           {selectedAgent?.status === 'running' ? (\n",
    "                              <div className=\"flex flex-col items-center justify-center h-full text-center space-y-8 animate-pulse text-slate-300\">\n",
    "                                 <Loader2 className=\"h-12 w-12 animate-spin\" />\n",
    "                                 <span className=\"text-[20px] font-black uppercase tracking-[0.2em]\">{selectedAgent.microStatus || \"Processing Matrix...\"}</span>\n",
    "                              </div>\n",
    "                           ) : !selectedAgent?.results ? (\n",
    "                              <div className=\"flex flex-col h-full items-center justify-center text-center opacity-30 grayscale pointer-events-none space-y-6\">\n",
    "                                 <Cpu className=\"h-12 w-12 text-slate-300\" />\n",
    "                                 <h2 className=\"text-3xl font-black uppercase tracking-[0.2em] text-slate-400\">Node Standby</h2>\n",
    "                              </div>\n",
    "                           ) : (\n",
    "                              <div className=\"flex-1 animate-in fade-in duration-500 overflow-hidden\">\n",
    "                                 {slides[activeSlide]?.type === 'chronology_module' ? (\n",
    "                                    <FactChronologyModule \n",
    "                                       initialItems={slides[activeSlide]?.content.items}\n",
    "                                       metadata={slides[activeSlide]?.content.metadata}\n",
    "                                       viewMode={factViewMode}\n",
    "                                       onViewModeChange={setFactViewMode}\n",
    "                                       selectedItemId={selectedRowId || undefined}\n",
    "                                       onSelectItem={handleSelectRow}\n",
    "                                       onSync={(newItems) => {\n",
    "                                          setAgents(prev => prev.map(a => a.id === 'fact' ? {\n",
    "                                             ...a,\n",
    "                                             results: {\n",
    "                                                ...a.results,\n",
    "                                                chronology_items: newItems\n",
    "                                             }\n",
    "                                          } : a));\n",
    "                                          toast.success(\"Chronology successfully synced to case intelligence.\");\n",
    "                                       }}\n",
    "                                    />\n",
    "                                 ) : (\n",
    "                                    <div className=\"flex flex-col h-full p-8\">\n",
    "                                       <h2 className=\"text-[32px] font-black text-slate-800 mb-8 tracking-tighter uppercase\">{slides[activeSlide]?.title}</h2>\n",
    "                                       {selectedAgentId === 'peepo' ? (\n",
    "                                          <div className=\"flex flex-col h-full bg-slate-50/10 animate-in fade-in duration-500 overflow-hidden\">\n",
    "                                             <div className=\"h-12 flex items-center justify-between px-5 border-b border-slate-200 bg-white shrink-0\">\n",
    "                                                <div className=\"flex items-center gap-2\">\n",
    "                                                   <div className=\"h-2 w-2 rounded-full bg-[#8ba861]\" />\n",
    "                                                   <h2 className=\"text-[10px] font-black text-slate-900 uppercase tracking-widest\">PEEPO Factor Analysis Sheet</h2>\n",
    "                                                </div>\n",
    "                                                <div className=\"flex items-center gap-2\">\n",
    "                                                   <div className=\"h-2 w-2 bg-emerald-500 rounded-full animate-pulse\" />\n",
    "                                                   <span className=\"text-[9px] font-bold text-slate-400 uppercase tracking-tight\">Synthesis Complete</span>\n",
    "                                                </div>\n",
    "                                             </div>\n",
    "                                             <div className=\"flex-1 overflow-auto p-6 scrollbar-thin\">\n",
    "                                                <div className=\"max-w-5xl mx-auto space-y-8 pb-12\">\n",
    "                                                   {[\n",
    "                                                      { id: 'people', label: 'People (Individu)' },\n",
    "                                                      { id: 'environment', label: 'Environment (Lingkungan)' },\n",
    "                                                      { id: 'equipment', label: 'Equipment (Peralatan)' },\n",
    "                                                      { id: 'procedures', label: 'Procedures (Prosedur)' },\n",
    "                                                      { id: 'organisation', label: 'Organisation (Organisasi)' },\n",
    "                                                   ].map((section) => (\n",
    "                                                      <div key={section.id} className=\"space-y-3\">\n",
    "                                                         <div className=\"flex items-center gap-3\">\n",
    "                                                            <span className=\"px-2.5 py-1 rounded text-[9px] font-black text-white uppercase tracking-widest bg-slate-900\">\n",
    "                                                               {section.label}\n",
    "                                                            </span>\n",
    "                                                            <div className=\"h-px flex-1 bg-slate-200\" />\n",
    "                                                         </div>\n",
    "                                                         <div className=\"bg-white border-l border-t border-slate-200 overflow-hidden shadow-sm\">\n",
    "                                                            <table className=\"w-full text-left border-collapse\">\n",
    "                                                               <thead>\n",
    "                                                                  <tr className=\"bg-slate-50/80\">\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-24 border-r border-b border-slate-200 bg-slate-50/30\">ID</th>\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest border-r border-b border-slate-200 bg-slate-50/30\">Forensic Finding</th>\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-32 border-r border-b border-slate-200 bg-slate-50/30\">Traceability</th>\n",
    "                                                                  </tr>\n",
    "                                                               </thead>\n",
    "                                                               <tbody>\n",
    "                                                                  {(selectedAgent?.results?.[section.id] || []).map((item: any, idx: number) => {\n",
    "                                                                     const isSelected = selectedRowId === (item.id || item);\n",
    "                                                                     return (\n",
    "                                                                        <tr \n",
    "                                                                           key={item.id || idx} \n",
    "                                                                           onClick={() => handleSelectRow(item.id || item)}\n",
    "                                                                           className={cn(\n",
    "                                                                              \"group transition-all cursor-pointer\",\n",
    "                                                                              isSelected ? \"bg-slate-100/80\" : \"hover:bg-slate-50/50\"\n",
    "                                                                           )}\n",
    "                                                                        >\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200\">\n",
    "                                                                              <span className=\"text-[11px] font-mono font-black text-slate-400\">#{section.id.slice(0, 1).toUpperCase()}{idx + 1}</span>\n",
    "                                                                           </td>\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200\">\n",
    "                                                                              <p className={cn(\n",
    "                                                                                 \"text-[11px] font-bold leading-relaxed pr-8\",\n",
    "                                                                                 isSelected ? \"text-slate-900\" : \"text-slate-700\"\n",
    "                                                                              )}>\n",
    "                                                                                 {item.label || item}\n",
    "                                                                              </p>\n",
    "                                                                           </td>\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200 text-center\">\n",
    "                                                                              <Search className={cn(\"h-3.5 w-3.5 mx-auto\", isSelected ? \"text-slate-900\" : \"text-slate-300\")} />\n",
    "                                                                           </td>\n",
    "                                                                        </tr>\n",
    "                                                                     );\n",
    "                                                                  })}\n",
    "                                                               </tbody>\n",
    "                                                            </table>\n",
    "                                                         </div>\n",
    "                                                      </div>\n",
    "                                                   ))}\n",
    "                                                   <div className=\"grid grid-cols-2 gap-6 pt-4\">\n",
    "                                                      <div className=\"bg-white border-l border-t border-slate-200 p-6 shadow-sm rounded-sm\">\n",
    "                                                         <span className=\"text-[9px] font-black text-slate-400 uppercase tracking-widest block mb-2\">Analysis Summary</span>\n",
    "                                                         <p className=\"text-[11px] font-bold text-slate-600 leading-relaxed italic\">\"{selectedAgent?.results?.ringkasan}\"</p>\n",
    "                                                      </div>\n",
    "                                                      <div className=\"bg-slate-900 p-6 shadow-sm border border-slate-800 rounded-sm\">\n",
    "                                                         <span className=\"text-[9px] font-black text-emerald-400/50 uppercase tracking-widest block mb-2\">Synthesis Intelligence</span>\n",
    "                                                         <p className=\"text-[11px] font-black text-white uppercase tracking-tight leading-relaxed\">{selectedAgent?.results?.synthesis}</p>\n",
    "                                                      </div>\n",
    "                                                   </div>\n",
    "                                                </div>\n",
    "                                             </div>\n",
    "                                          </div>\n",
    "                                       ) : selectedAgentId === 'ipls' ? (\n",
    "                                          <div className=\"flex flex-col h-full bg-slate-50/10 animate-in fade-in duration-500 overflow-hidden\">\n",
    "                                             <div className=\"h-12 flex items-center justify-between px-5 border-b border-slate-200 bg-white shrink-0\">\n",
    "                                                <div className=\"flex items-center gap-2\">\n",
    "                                                   <div className=\"h-2 w-2 rounded-full bg-[#8ba861]\" />\n",
    "                                                   <h2 className=\"text-[10px] font-black text-slate-900 uppercase tracking-widest\">Integrated Profile Layer (IPLS) Sheet</h2>\n",
    "                                                </div>\n",
    "                                                <div className=\"flex items-center gap-2\">\n",
    "                                                   <div className=\"h-2 w-2 bg-emerald-500 rounded-full animate-pulse\" />\n",
    "                                                   <span className=\"text-[9px] font-bold text-slate-400 uppercase tracking-tight\">Defensive Audit Complete</span>\n",
    "                                                </div>\n",
    "                                             </div>\n",
    "                                             <div className=\"flex-1 overflow-auto p-6 scrollbar-thin\">\n",
    "                                                <div className=\"max-w-[1400px] mx-auto space-y-8 pb-12\">\n",
    "                                                   {(selectedAgent?.results?.layers || []).map((layer: any) => (\n",
    "                                                      <div key={layer.id} className=\"space-y-3\">\n",
    "                                                         <div className=\"flex items-center gap-3\">\n",
    "                                                            <span className=\"px-2.5 py-1 rounded text-[9px] font-black text-white uppercase tracking-widest bg-slate-900\">\n",
    "                                                               Layer {[\"I\", \"II\", \"III\", \"IV\", \"V\"][layer.id - 1]}: {layer.title}\n",
    "                                                            </span>\n",
    "                                                            <div className=\"h-px flex-1 bg-slate-200\" />\n",
    "                                                         </div>\n",
    "                                                         <div className=\"bg-white border-l border-t border-slate-200 overflow-hidden shadow-sm\">\n",
    "                                                            <table className=\"w-full text-left border-collapse\">\n",
    "                                                               <thead>\n",
    "                                                                  <tr className=\"bg-slate-50/80\">\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-24 border-r border-b border-slate-200 bg-slate-50/30\">STATUS</th>\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest border-r border-b border-slate-200 bg-slate-50/30\">Defensive Audit Point</th>\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-32 border-r border-b border-slate-200 bg-slate-50/30\">Traceability</th>\n",
    "                                                                  </tr>\n",
    "                                                               </thead>\n",
    "                                                               <tbody>\n",
    "                                                                  {layer.items.map((item: any, idx: number) => {\n",
    "                                                                     const isSelected = selectedRowId === item.id;\n",
    "                                                                     return (\n",
    "                                                                        <tr \n",
    "                                                                           key={item.id || idx} \n",
    "                                                                           onClick={() => handleSelectRow(item.id)}\n",
    "                                                                           className={cn(\n",
    "                                                                              \"group transition-all cursor-pointer\",\n",
    "                                                                              isSelected ? \"bg-slate-100/80\" : \"hover:bg-slate-50/50\"\n",
    "                                                                           )}\n",
    "                                                                        >\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200\">\n",
    "                                                                              <div className=\"flex justify-center\">\n",
    "                                                                                 {item.status === 'rootcause' ? (\n",
    "                                                                                    <div className=\"h-4 w-4 rounded-full border-2 border-red-500 flex items-center justify-center\">\n",
    "                                                                                       <div className=\"h-1.5 w-1.5 rounded-full bg-red-500\" />\n",
    "                                                                                    </div>\n",
    "                                                                                 ) : item.status === 'non-conformity' ? (\n",
    "                                                                                    <div className=\"h-4 w-4 rounded-full border-2 border-amber-500 flex items-center justify-center\">\n",
    "                                                                                       <div className=\"h-1.5 w-1.5 rounded-full bg-amber-500\" />\n",
    "                                                                                    </div>\n",
    "                                                                                 ) : (\n",
    "                                                                                    <div className=\"h-4 w-4 rounded-full border-2 border-emerald-500 flex items-center justify-center\">\n",
    "                                                                                       <div className=\"h-1.5 w-1.5 rounded-full bg-emerald-500\" />\n",
    "                                                                                    </div>\n",
    "                                                                                 )}\n",
    "                                                                              </div>\n",
    "                                                                           </td>\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200\">\n",
    "                                                                              <p className={cn(\n",
    "                                                                                 \"text-[11px] font-bold leading-relaxed pr-8\",\n",
    "                                                                                 isSelected ? \"text-slate-900\" : \"text-slate-700\"\n",
    "                                                                              )}>\n",
    "                                                                                 {item.label}\n",
    "                                                                              </p>\n",
    "                                                                           </td>\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200 text-center\">\n",
    "                                                                              <Search className={cn(\"h-3.5 w-3.5 mx-auto\", isSelected ? \"text-slate-900\" : \"text-slate-300\")} />\n",
    "                                                                           </td>\n",
    "                                                                        </tr>\n",
    "                                                                     );\n",
    "                                                                  })}\n",
    "                                                               </tbody>\n",
    "                                                            </table>\n",
    "                                                         </div>\n",
    "                                                      </div>\n",
    "                                                   ))}\n",
    "                                                </div>\n",
    "                                             </div>\n",
    "                                          </div>\n",
    "                                       ) : selectedAgentId === 'prev' ? (\n",
    "                                          <div className=\"flex flex-col h-full bg-slate-50/10 animate-in fade-in duration-500 overflow-hidden\">\n",
    "                                             <div className=\"h-12 flex items-center justify-between px-5 border-b border-slate-200 bg-white shrink-0\">\n",
    "                                                <div className=\"flex items-center gap-2\">\n",
    "                                                   <div className=\"h-2 w-2 rounded-full bg-[#8ba861]\" />\n",
    "                                                   <h2 className=\"text-[10px] font-black text-slate-900 uppercase tracking-widest\">Prevention Action Plan Sheet</h2>\n",
    "                                                </div>\n",
    "                                                <div className=\"flex items-center gap-2\">\n",
    "                                                   <div className=\"h-2 w-2 bg-emerald-500 rounded-full animate-pulse\" />\n",
    "                                                   <span className=\"text-[9px] font-bold text-slate-400 uppercase tracking-tight\">Plan Finalized</span>\n",
    "                                                </div>\n",
    "                                             </div>\n",
    "                                             <div className=\"flex-1 overflow-auto p-6 scrollbar-thin\">\n",
    "                                                <div className=\"max-w-[1600px] mx-auto space-y-10 pb-12\">\n",
    "                                                   {[\n",
    "                                                      { id: 'root', title: 'Root Cause Actions', color: 'bg-red-500', data: selectedAgent?.results?.root_cause_actions },\n",
    "                                                      { id: 'nc', title: 'Non Conformity Actions', color: 'bg-amber-500', data: selectedAgent?.results?.non_conformity_actions },\n",
    "                                                      { id: 'imp', title: 'Improvement Actions', color: 'bg-emerald-500', data: selectedAgent?.results?.improvement_actions },\n",
    "                                                   ].map((section) => (\n",
    "                                                      <div key={section.id} className=\"space-y-3\">\n",
    "                                                         <div className=\"flex items-center gap-3\">\n",
    "                                                            <span className={cn(\"px-2.5 py-1 rounded text-[9px] font-black text-white uppercase tracking-widest\", section.color)}>\n",
    "                                                               {section.title}\n",
    "                                                            </span>\n",
    "                                                            <div className=\"h-px flex-1 bg-slate-200\" />\n",
    "                                                         </div>\n",
    "                                                         <div className=\"bg-white border-l border-t border-slate-200 overflow-hidden shadow-sm\">\n",
    "                                                            <table className=\"w-full text-left border-collapse\">\n",
    "                                                               <thead>\n",
    "                                                                  <tr className=\"bg-slate-50/80\">\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-12 border-r border-b border-slate-200 bg-slate-50/30\">NO</th>\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-24 border-r border-b border-slate-200 bg-slate-50/30\">LAYER</th>\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-32 border-r border-b border-slate-200 bg-slate-50/30\">CONTROL</th>\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest border-r border-b border-slate-200 bg-slate-50/30\">Prevention Action</th>\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-32 border-r border-b border-slate-200 bg-slate-50/30\">PIC</th>\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-24 border-r border-b border-slate-200 bg-slate-50/30\">DUE DATE</th>\n",
    "                                                                     <th className=\"px-5 py-3 text-[10px] font-black text-slate-500 uppercase tracking-widest w-24 border-b border-slate-200 bg-slate-50/30 text-center\">STATUS</th>\n",
    "                                                                  </tr>\n",
    "                                                               </thead>\n",
    "                                                               <tbody>\n",
    "                                                                  {(section.data || []).map((item: any, idx: number) => {\n",
    "                                                                     const isSelected = selectedRowId === item.id;\n",
    "                                                                     return (\n",
    "                                                                        <tr \n",
    "                                                                           key={item.id || idx} \n",
    "                                                                           onClick={() => handleSelectRow(item.id)}\n",
    "                                                                           className={cn(\n",
    "                                                                              \"group transition-all cursor-pointer\",\n",
    "                                                                              isSelected ? \"bg-slate-100/80\" : \"hover:bg-slate-50/50\"\n",
    "                                                                           )}\n",
    "                                                                        >\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200 text-center text-[11px] font-mono font-black text-slate-400\">\n",
    "                                                                              {item.no}\n",
    "                                                                           </td>\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200 text-center text-[10px] font-black text-slate-500 uppercase\">\n",
    "                                                                              {item.layer}\n",
    "                                                                           </td>\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200 text-center text-[10px] font-black text-slate-900 uppercase tracking-tighter\">\n",
    "                                                                              {item.hierarchy}\n",
    "                                                                           </td>\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200\">\n",
    "                                                                              <p className={cn(\n",
    "                                                                                 \"text-[11px] font-bold leading-relaxed pr-8 uppercase tracking-tight\",\n",
    "                                                                                 isSelected ? \"text-slate-900\" : \"text-slate-700\"\n",
    "                                                                              )}>\n",
    "                                                                                 {item.action}\n",
    "                                                                              </p>\n",
    "                                                                           </td>\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200 text-center text-[10px] font-bold text-slate-600\">\n",
    "                                                                              {item.pic}\n",
    "                                                                           </td>\n",
    "                                                                           <td className=\"px-5 py-4 align-top border-r border-b border-slate-200 text-center text-[10px] font-mono text-slate-500\">\n",
    "                                                                              {item.due_date}\n",
    "                                                                           </td>\n",
    "                                                                           <td className=\"p-0 border-b border-slate-200\">\n",
    "                                                                              <div className={cn(\n",
    "                                                                                 \"h-12 flex items-center justify-center text-[9px] font-black tracking-widest uppercase\",\n",
    "                                                                                 item.status === 'OPEN' ? \"bg-red-50 text-red-600\" :\n",
    "                                                                                 item.status === 'PROGRESS' ? \"bg-amber-50 text-amber-600\" :\n",
    "                                                                                 \"bg-emerald-50 text-emerald-600\"\n",
    "                                                                              )}>\n",
    "                                                                                 {item.status}\n",
    "                                                                              </div>\n",
    "                                                                           </td>\n",
    "                                                                        </tr>\n",
    "                                                                     );\n",
    "                                                                  })}\n",
    "                                                               </tbody>\n",
    "                                                            </table>\n",
    "                                                         </div>\n",
    "                                                      </div>\n",
    "                                                   ))}\n",
    "                                                </div>\n",
    "                                             </div>\n",
    "                                          </div>\n",
    "                                       ) : (\n",
    "                                          <div className=\"flex-1 bg-[#1a1c23] rounded-sm p-6 overflow-hidden border border-slate-700 relative\">\n",
    "                                             <pre className=\"text-[12px] font-mono text-emerald-400/90 leading-tight h-full overflow-auto custom-scrollbar\">\n",
    "                                                {JSON.stringify(slides[activeSlide]?.content, null, 2)}\n",
    "                                             </pre>\n",
    "                                          </div>\n",
    "                                       )}\n",
    "                                    </div>\n",
    "                                 )}\n",
    "                              </div>\n",
    "                           )}\n",
    "                        </div>\n",
    "                     </div>\n",
    "                  ) : (\n",
    "                     <div className=\"flex-1 flex flex-col items-center justify-center p-12 text-slate-300\">\n",
    "                        <Brain className=\"h-12 w-12 mb-4 opacity-20\" />\n",
    "                        <h2 className=\"text-3xl font-black uppercase tracking-[0.2em] text-slate-400\">Orchestration Idle</h2>\n",
    "                        <p className=\"text-[10px] mt-2 opacity-50 font-bold uppercase\">Select a node to view intelligence results</p>\n",
    "                     </div>\n",
    "                  )}\n"
]

final_lines = lines[:start_index] + new_orchestration + lines[end_index:]

with open(file_path, 'w', encoding='utf-8') as f:
    f.writelines(final_lines)
