const fs = require('fs');

const CACHE_FILE = 'src/pages/CaseWorkspacePage.tsx';
let text = fs.readFileSync(CACHE_FILE, 'utf8');

// 1. Add microStatus to AgentState
if (!text.includes('microStatus?: string;')) {
    text = text.replace('interface AgentState {', 'interface AgentState {\n  microStatus?: string;');
}

// 2. Replace the orchestration useEffect and helper functions
const analysisTabStart = text.indexOf('function AnalysisTab()');
const useEffectStart = text.indexOf('useEffect(() =>', analysisTabStart);
const useEffectEnd = text.indexOf('}, [chainQueue, activeTask, globalStatus, agents, execMode]);', useEffectStart);

if (useEffectStart !== -1 && useEffectEnd !== -1) {
    const newEffect = `useEffect(() => {
    if (globalStatus === 'running' && !activeTask && chainQueue.length > 0) {
      const nextId = chainQueue[0];
      const agent = agents.find(a => a.id === nextId)!;
      
      const depsFailedOrBlocked = agent.dependencies.some(dId => {
        const d = agents.find(x => x.id === dId)!;
        return d.status === 'failed' || d.status === 'blocked';
      });

      if (depsFailedOrBlocked && (execMode === "full" || execMode === "manual")) {
        setGlobalStatus('blocked');
        setAgents(prev => prev.map(a => a.id === nextId ? { ...a, status: 'blocked', dependencyState: 'Blocked', microStatus: 'Waiting for upstream...' } : a));
        return;
      }

      setActiveTask(nextId);
      if (execMode === 'full') {
          setSelectedAgentId(nextId);
      }
      setAgents(prev => prev.map(a => a.id === nextId ? { 
          ...a, 
          status: 'running', 
          microStatus: 'Initializing engine context...', 
          triggeredBy: execMode === 'full' ? 'System' : 'Current User' 
      } : a));

      // Simulate micro-execution steps
      const stages = [
          'Reading evidence batches...',
          'Mapping involved entities...',
          'Synthesizing workspace findings...',
          'Applying industrial safety logic...',
          'Finalizing output schema...'
      ];
      stages.forEach((msg, idx) => {
          setTimeout(() => {
              setAgents(prev => prev.map(a => a.id === nextId ? { ...a, microStatus: msg } : a));
          }, (idx + 1) * 700);
      });

      setTimeout(() => {
        const d = new Date();
        setAgents(prev => {
          const a = prev.find(x => x.id === nextId);
          if (a?.status === 'running') {
            return prev.map(x => x.id === nextId ? { 
              ...x, 
              status: 'completed', 
              lastRunTimestamp: d.toLocaleTimeString(),
              lastUpdatedTimestamp: d.toLocaleTimeString(),
              confidence: (85 + Math.floor(Math.random() * 10)) + "%",
              dependencyState: 'Resolved',
              microStatus: 'Synthesis complete.'
            } : x);
          }
          return prev;
        });

        setAgents(currentAgents => {
           const finalA = currentAgents.find(x => x.id === nextId);
           if (finalA?.status === 'completed' || finalA?.status === 'warning') {
              setHistory(h => [{
                 runId: \`RUN-\${Math.floor(Math.random()*1000).toString().padStart(3,'0')}\`,
                 agent: finalA.name,
                 triggeredBy: finalA.triggeredBy || "System",
                 mode: execMode === "full" ? "Auto" : "Manual",
                 inputSource: "Context",
                 deps: finalA.dependencies.length > 0 ? "Resolved" : "None",
                 status: finalA.status,
                 started: d.toLocaleTimeString(),
                 finished: new Date(d.getTime() + 3000).toLocaleTimeString(),
                 duration: "3s"
              }, ...h]);
           }
           
           if (execMode === 'full') {
               return currentAgents.map(a => {
                   if (a.status === 'idle' && a.dependencies.every(dId => currentAgents.find(x => x.id === dId)?.status === 'completed')) {
                       return { ...a, dependencyState: 'Ready' };
                   }
                   return a;
               })
           }
           return currentAgents;
        });

        setChainQueue(q => q.slice(1));
        setActiveTask(null);
      }, 4000);
    } else if (globalStatus === 'running' && !activeTask && chainQueue.length === 0) {
      setGlobalStatus('completed');
    }
  }, [chainQueue, activeTask, globalStatus, agents, execMode]);`;
    text = text.substring(0, useEffectStart) + newEffect + text.substring(useEffectEnd + 61);
}

// 3. Update the return block
// To avoid escaping hell, I'll read a placeholder from another file or just use string replacement carefully.
// I'll use a very specific start and end for the return block.

const anchor = '}function ReportsTab()';
const anchorIdx = text.indexOf(anchor);
const returnIdx = text.indexOf('return (', analysisTabStart);
const lastReturnEnd = text.lastIndexOf(');', anchorIdx);
const endIdx = lastReturnEnd + 2;

if (returnIdx !== -1 && endIdx !== -1) {
    // I'll use a simpler replace method for the return block to avoid string literal issues
    // I already have the new block content, I'll just write it carefully.
    
    const blockContent = [
        'return (',
        '    <div className="flex flex-col h-full bg-[#f4f5f7]">',
        '      {/* GLOBAL HEADER BAR */}',
        '      <div className="h-14 bg-white border-b border-slate-200 px-6 flex items-center justify-between shrink-0 z-30 shadow-sm relative">',
        '         <div className="flex items-center gap-4">',
        '            <div className="flex flex-col">',
        '                <h2 className="text-[15px] font-bold text-slate-800 tracking-tight flex items-center gap-2">',
        '                   Mining Intelligence & Analytics',
        '                   {globalStatus === \'running\' && <span className="flex h-1.5 w-1.5 rounded-full bg-blue-500 animate-pulse" />}',
        '                </h2>',
        '                <div className="flex items-center gap-2 mt-0.5">',
        '                   <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Active Pipeline: CS-2026-0147</span>',
        '                   <span className="h-1 w-1 rounded-full bg-slate-300" />',
        '                   <span className="text-[9px] font-bold text-slate-500 uppercase tracking-widest leading-none">',
        '                      {execMode === \'full\' ? \'Sequential Orchestration Mode\' : execMode === \'manual\' ? \'Isolated Manual Context\' : \'Matrix Standby\'}',
        '                   </span>',
        '                </div>',
        '            </div>',
        '         </div>',
        '         <div className="flex items-center gap-3">',
        '            {globalStatus === \'running\' ? (',
        '               <Button onClick={stopChain} variant="destructive" className="h-8 text-[10px] font-bold gap-1.5 px-4 bg-rose-600 hover:bg-rose-700 shadow-sm border-none text-white transition-all"><StopCircle className="h-3.5 w-3.5" /> Stop Pipeline</Button>',
        '            ) : globalStatus === \'blocked\' ? (',
        '               <Button onClick={continueChain} className="h-8 text-[10px] font-bold gap-1.5 px-4 bg-amber-500 hover:bg-amber-600 shadow-sm border-none text-white transition-all"><FastForward className="h-3.5 w-3.5" /> Resume Chain</Button>',
        '            ) : (',
        '               <Button onClick={startFullChain} className="h-8 text-[10px] font-bold gap-2 px-6 bg-slate-800 hover:bg-black shadow-lg shadow-slate-200 border-none text-white transition-all hover:scale-[1.02] active:scale-[0.98]">',
        '                  <Play className="h-3 w-3" fill="currentColor" /> Initialize Full Intelligence Chain',
        '               </Button>',
        '            )}',
        '            <div className="w-px h-6 bg-slate-200 mx-1" />',
        '            <Button variant="outline" className="h-8 px-3 border-slate-200 text-slate-500 hover:text-slate-800 text-[10px] font-bold gap-2"><History className="h-4 w-4" /> Trace Logs</Button>',
        '            <Button variant="outline" className="h-8 w-8 p-0 border-slate-200 text-slate-400 hover:text-slate-800"><Settings className="h-4 w-4" /></Button>',
        '         </div>',
        '      </div>',
        '',
        '      <div className="flex-1 flex overflow-hidden">',
        '         {/* PANEL 1: LEFT - ENGINE STACK (340px) */}',
        '         <div className="w-[340px] border-r border-slate-200 bg-[#FCFCFD] flex flex-col shrink-0 z-10 shadow-[2px_0_10px_rgba(0,0,0,0.02)]">',
        '            <div className="p-4 border-b border-slate-100 flex items-center justify-between bg-white/50 shrink-0">',
        '               <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest px-1">Engine Matrix Nodes</span>',
        '               <div className="text-[9px] font-black text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded border border-emerald-100 uppercase">{stats.completed}/{stats.total} Contexts Ready</div>',
        '            </div>',
        '            <div className="flex-1 overflow-y-auto p-3 space-y-3 custom-scrollbar bg-slate-50/20">',
        '               {agents.map((agent) => {',
        '                  const isSelected = selectedAgentId === agent.id;',
        '                  const isActive = activeTask === agent.id;',
        '                  const isQueued = chainQueue.includes(agent.id) && !isActive;',
        '                  ',
        '                  return (',
        '                    <div ',
        '                       key={agent.id} ',
        '                       onClick={() => setSelectedAgentId(agent.id)}',
        '                       className={`group relative p-4 rounded-xl border transition-all cursor-pointer ${',
        '                          isSelected ',
        '                          ? \'bg-white border-blue-500 shadow-[0_8px_20px_-8px_rgba(59,130,246,0.15)] ring-1 ring-blue-500/10\' ',
        '                          : \'bg-white border-slate-200 hover:border-slate-300 hover:shadow-sm\'',
        '                       } ${isActive ? \'ring-2 ring-blue-500/20\' : \'\'}`}',
        '                    >',
        '                       {/* Status Indicator Strip */}',
        '                       <div className={`absolute top-0 left-4 right-4 h-[3px] rounded-b-full transition-all ${',
        '                           agent.status === \'completed\' ? \'bg-emerald-500 shadow-[0_2px_4px_rgba(16,185,129,0.3)]\' :',
        '                           agent.status === \'running\' ? \'bg-blue-500 animate-pulse shadow-[0_2px_4px_rgba(59,130,246,0.3)]\' :',
        '                           agent.status === \'blocked\' ? \'bg-amber-500 shadow-[0_2px_4px_rgba(245,158,11,0.3)]\' :',
        '                           agent.status === \'failed\' ? \'bg-rose-500\' :',
        '                           isQueued ? \'bg-slate-300\' : \'bg-slate-100\'',
        '                       }`} />',
        '',
        '                       <div className="flex items-start gap-4 mt-1">',
        '                          <div className={`mt-1 h-9 w-9 rounded-lg flex items-center justify-center border shadow-sm transition-colors ${',
        '                             isSelected ? \'bg-blue-600 border-blue-500 text-white\' : \'bg-slate-50 border-slate-200 text-slate-400\'',
        '                          }`}>',
        '                             <agent.icon className="h-4.5 w-4.5" />',
        '                          </div>',
        '                          <div className="flex-1 min-w-0">',
        '                             <div className="flex items-center justify-between mb-0.5">',
        '                                <h3 className={`text-[13px] font-bold tracking-tight truncate ${isSelected ? \'text-blue-600\' : \'text-slate-800\'}`}>{agent.name}</h3>',
        '                                <div className={`flex items-center gap-1.5 px-2 py-0.5 rounded border ${getStatusColor(agent.status)}`}>',
        '                                   {agent.status === \'running\' && <Loader2 className="h-2 w-2 animate-spin" />}',
        '                                   <span className="text-[8px] font-black uppercase tracking-widest leading-none translate-y-[0.5px]">{agent.status}</span>',
        '                                </div>',
        '                             </div>',
        '                             ',
        '                             {/* Agent Micro-Status Feedback */}',
        '                             {isActive ? (',
        '                                <div className="flex flex-col gap-1 mb-3 bg-blue-50/50 p-2 rounded-lg border border-blue-100/50">',
        '                                   <div className="flex items-center gap-2">',
        '                                      <Loader2 className="h-2.5 w-2.5 text-blue-500 animate-spin" />',
        '                                      <span className="text-[9px] font-black text-blue-600 uppercase tracking-tight italic animate-pulse">',
        '                                         {agent.microStatus || "Processing Matrix..."}',
        '                                      </span>',
        '                                   </div>',
        '                                   <div className="h-1 bg-blue-100 rounded-full overflow-hidden">',
        '                                      <div className="h-full bg-blue-500 transition-all duration-700 ease-linear" style={{ width: \'60%\' }} />',
        '                                   </div>',
        '                                </div>',
        '                             ) : (',
        '                                <p className="text-[10px] text-slate-400 font-medium leading-tight mb-3 line-clamp-1">{agent.purpose}</p>',
        '                             )}',
        '                             ',
        '                             <div className="grid grid-cols-2 gap-x-4 gap-y-2.5 border-t border-slate-100 pt-3">',
        '                                <div className="flex flex-col">',
        '                                   <span className="text-[8px] font-black text-slate-400 uppercase tracking-[0.15em] leading-none mb-1.5">Confidence</span>',
        '                                   <span className="text-[10px] font-black text-slate-700 leading-none">{agent.confidence || "WAITING"}</span>',
        '                                </div>',
        '                                <div className="flex flex-col items-end text-right">',
        '                                   <span className="text-[8px] font-black text-slate-400 uppercase tracking-[0.15em] leading-none mb-1.5">Dependency</span>',
        '                                   <span className={`text-[9px] font-black uppercase tracking-tight leading-none ${agent.dependencyState === \'Resolved\' ? \'text-emerald-600\' : \'text-slate-400\'}`}>{agent.dependencyState || "Ready"}</span>',
        '                                </div>',
        '                                <div className="flex flex-col">',
        '                                   <span className="text-[8px] font-black text-slate-400 uppercase tracking-[0.15em] leading-none mb-1.5">Last Epoch</span>',
        '                                   <span className="text-[10px] font-black text-slate-700 leading-none">{agent.lastRunTimestamp ? agent.lastRunTimestamp.split(\' \')[0] : "None"}</span>',
        '                                </div>',
        '                                <div className="flex items-center justify-end gap-1.5">',
        '                                   <Button ',
        '                                      size="sm" ',
        '                                      variant="ghost" ',
        '                                      onClick={(e) => runSingle(agent.id, e)}',
        '                                      disabled={globalStatus === \'running\'}',
        '                                      title="Manual Override"',
        '                                      className="h-6 w-6 p-0 rounded-md hover:bg-slate-900 hover:text-white text-slate-400 border border-slate-100 transition-all active:scale-90"',
        '                                   >',
        '                                      <Play className="h-2.5 w-2.5" fill="currentColor" />',
        '                                   </Button>',
        '                                   <Button ',
        '                                      size="sm" ',
        '                                      variant="ghost" ',
        '                                      title="Inspect Node Config"',
        '                                      className="h-6 w-6 p-0 rounded-md bg-slate-50 text-slate-300 hover:bg-slate-200 transition-all"',
        '                                   >',
        '                                      <Settings className="h-2.5 w-2.5" />',
        '                                   </Button>',
        '                                </div>',
        '                             </div>',
        '                          </div>',
        '                       </div>',
        '                    </div>',
        '                  );',
        '               })}',
        '            </div>',
        '            ',
        '            <div className="p-4 border-t border-slate-100 bg-white/50 shrink-0">',
        '               <div className="flex items-center justify-between mb-2 px-1">',
        '                  <span className="text-[9px] font-black text-slate-400 uppercase tracking-widest">Downstream Logic Pipe</span>',
        '                  <Activity className="h-3 w-3 text-slate-200" />',
        '               </div>',
        '               <div className="grid grid-cols-5 gap-1.5">',
        '                  {agents.map(a => (',
        '                     <div key={`pipe-${a.id}`} className={`h-1.5 rounded-full transition-all ${',
        '                         a.status === \'completed\' ? \'bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.3)]\' :',
        '                         a.status === \'running\' ? \'bg-blue-500 animate-pulse shadow-[0_0_8px_rgba(59,130,246,0.3)]\' :',
        '                         a.status === \'failed\' ? \'bg-rose-500\' : \'bg-slate-200\'',
        '                     }`} />',
        '                  ))}',
        '               </div>',
        '            </div>',
        '         </div>',
        '',
        '         {/* PANEL 2: CENTER - RESULT CANVAS (Dominant) */}',
        '         <div className="flex-1 bg-[#EEF0F5] flex flex-col relative overflow-hidden custom-scrollbar">',
        '            {/* Background Architecture Grid */}',
        '            <div className="absolute inset-0 opacity-[0.04] pointer-events-none" style={{ backgroundImage: \'linear-gradient(#1e293b 1px, transparent 1px), linear-gradient(90deg, #1e293b 1px, transparent 1px)\', backgroundSize: \'40px 40px\' }} />',
        '            ',
        '            {/* AGENTIC EXECUTION STRIP (Rule 1) */}',
        '            <div className="h-16 bg-white border-b border-slate-200 px-8 flex items-center justify-center shrink-0 z-20 shadow-sm relative overflow-hidden">',
        '               {/* Background Progress Bar for full chain */}',
        '               {execMode === \'full\' && (',
        '                  <div className="absolute top-0 left-0 right-0 h-[2px] bg-slate-100">',
        '                     <div ',
        '                        className="h-full bg-blue-500 transition-all duration-1000 ease-in-out shadow-[0_0_10px_rgba(59,130,246,0.5)]" ',
        '                        style={{ width: `${(stats.completed / stats.total) * 100}%` }}',
        '                     />',
        '                  </div>',
        '               )}',
        '',
        '               <div className="flex items-center justify-between w-full max-w-[1000px] relative">',
        '                  {agents.map((a, i) => {',
        '                      const isActive = activeTask === a.id;',
        '                      const isComplete = a.status === \'completed\';',
        '                      const isSelected = selectedAgentId === a.id;',
        '',
        '                      return (',
        '                         <React.Fragment key={`strip-node-${a.id}`}>',
        '                            <div ',
        '                               onClick={() => setSelectedAgentId(a.id)}',
        '                               className={`relative flex flex-col items-center group cursor-pointer transition-all ${isSelected ? \'scale-110\' : \'opacity-60 hover:opacity-100\'}`}',
        '                            >',
        '                               <div className={`h-10 w-10 rounded-full border-2 flex items-center justify-center bg-white shadow-sm transition-all duration-300 ${',
        '                                   isActive ? \'border-blue-600 shadow-[0_0_15px_rgba(59,130,246,0.2)] ring-4 ring-blue-500/10\' :',
        '                                   isComplete ? \'border-emerald-500 bg-emerald-50 text-emerald-600\' :',
        '                                   isSelected ? \'border-slate-800\' : \'border-slate-200\'',
        '                               }`}>',
        '                                  {isActive ? <Loader2 className="h-5 w-5 text-blue-600 animate-spin" /> :',
        '                                   isComplete ? <Check className="h-5 w-5" strokeWidth={3} /> :',
        '                                   <a.icon className={`h-4.5 w-4.5 ${isSelected ? \'text-slate-800\' : \'text-slate-300\'}`} />}',
        '                               </div>',
        '                               <div className={`absolute -bottom-5 flex flex-col items-center transition-all ${isSelected ? \'opacity-100\' : \'opacity-0 translate-y-2\'}`}',
        '                               >',
        '                                  <span className="text-[9px] font-black uppercase tracking-widest text-blue-600 mb-0.5">{a.name.split(\' \')[0]}</span>',
        '                                  {isActive && <div className="h-1 w-1 rounded-full bg-blue-500 animate-bounce" />}',
        '                               </div>',
        '                            </div>',
        '                            {i < agents.length - 1 && (',
        '                               <div className="flex-1 px-4 relative">',
        '                                  <div className="h-[2px] w-full bg-slate-100 rounded-full" />',
        '                                  <div ',
        '                                     className={`absolute top-0 left-4 right-4 h-[2px] transition-all duration-1000 ${isComplete ? \'bg-emerald-500\' : isActive ? \'bg-blue-200\' : \'bg-transparent\'}`} ',
        '                                     style={{ width: isComplete ? \'calc(100% - 32px)\' : \'0%\' }}',
        '                                  />',
        '                                  {isActive && (',
        '                                     <ArrowRight className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-3 w-3 text-blue-400 opacity-50 animate-pulse" />',
        '                                  )}',
        '                               </div>',
        '                            )}',
        '                         </React.Fragment>',
        '                      );',
        '                  })}',
        '               </div>',
        '            </div>',
        '',
        '            <div className="flex-1 overflow-auto p-8 flex flex-col items-center justify-start min-h-0 relative">',
        '                {!selectedAgentId ? (',
        '                    <div className="py-24 flex flex-col items-center text-center max-w-sm animate-in fade-in zoom-in-95 duration-500">',
        '                        <div className="h-24 w-24 rounded-[3.rem] bg-white border border-slate-200 shadow-2xl flex items-center justify-center mb-10 rotate-12 transition-transform hover:rotate-0">',
        '                            <Brain className="h-10 w-10 text-slate-200 shadow-inner" />',
        '                        </div>',
        '                        <h3 className="text-xl font-black text-slate-800 tracking-tighter mb-3 uppercase">Orchestration Standby</h3>',
        '                        <p className="text-[14px] text-slate-400 font-medium leading-relaxed mb-10">Select an intelligence node from the execution matrix or initialize the full chain to begin workspace synthesis.</p>',
        '                        <Button onClick={startFullChain} className="bg-slate-900 shadow-2xl h-11 px-10 rounded-2xl text-[11px] font-black uppercase tracking-widest gap-2.5 transition-all hover:scale-105 active:scale-95">',
        '                           Initialize Full Pipeline <Zap className="h-4 w-4 fill-amber-400 text-amber-400" />',
        '                        </Button>',
        '                    </div>',
        '                ) : (',
        '                    <div className="flex flex-col items-center gap-6 w-full h-full relative z-10 max-w-[1240px]">',
        '                        ',
        '                        {/* AGENT CONTEXT BAR (Rule 5) */}',
        '                        <div className={`w-full bg-white border border-slate-200 rounded-2xl px-8 py-3.5 flex items-center justify-between shadow-[0_10px_30px_rgba(0,0,0,0.04)] animate-in slide-in-from-top-4 transition-all ${selectedAgent?.status === \'running\' ? \'border-blue-200 shadow-[0_10px_30px_rgba(59,130,246,0.1)]\' : \'\'}`}',
        '                        >',
        '                            <div className="flex items-center gap-8">',
        '                                <div className="flex items-center gap-4">',
        '                                   <div className={`h-10 w-10 rounded-xl bg-slate-50 border border-slate-100 flex items-center justify-center transition-all ${selectedAgent?.status === \'running\' ? \'border-blue-200 text-blue-600 bg-blue-50/50\' : \'text-slate-400\'}`}',
        '                                   >',
        '                                      {selectedAgent?.icon && <selectedAgent.icon className="h-5 w-5" />}',
        '                                   </div>',
        '                                   <div>',
        '                                      <div className="flex items-center gap-2 mb-1">',
        '                                         <h4 className="text-[12px] font-black text-slate-900 uppercase tracking-[0.1em] leading-none">{selectedAgent?.name}</h4>',
        '                                         <div className={`h-1.5 w-1.5 rounded-full ${selectedAgent?.status === \'completed\' ? \'bg-emerald-500\' : selectedAgent?.status === \'running\' ? \'bg-blue-500 animate-pulse\' : \'bg-slate-300\'}`} />',
        '                                      </div>',
        '                                      <div className="flex items-center gap-3">',
        '                                         <div className="flex items-center gap-1.5">',
        '                                            <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Epoch:</span>',
        '                                            <span className="text-[9px] font-black text-slate-700 uppercase">{selectedAgent?.lastRunTimestamp || \'Pending\'}</span>',
        '                                         </div>',
        '                                         <div className="h-1 w-1 rounded-full bg-slate-200" />',
        '                                         <div className="flex items-center gap-1.5">',
        '                                            <span className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Conf:</span>',
        '                                            <span className="text-[9px] font-black text-emerald-600 uppercase">{selectedAgent?.confidence || \'0%\'}</span>',
        '                                         </div>',
        '                                      </div>',
        '                                   </div>',
        '                                </div>',
        '                                <div className="w-px h-8 bg-slate-100" />',
        '                                <div className="flex items-center gap-6">',
        '                                   <div className="flex flex-col">',
        '                                      <span className="text-[8px] font-black text-slate-300 uppercase tracking-widest leading-none mb-1.5">Execution Mode</span>',
        '                                      <div className="flex items-center gap-1.5">',
        '                                         <div className={`h-0.5 w-3 rounded-full ${execMode === \'full\' ? \'bg-blue-600 shadow-[0_0_5px_rgba(59,130,246,0.8)]\' : \'bg-slate-300\'}`} />',
        '                                         <span className="text-[10px] font-black text-slate-600 uppercase tracking-tighter">{execMode === \'full\' ? \'Sequential\' : execMode === \'manual\' ? \'Isolated\' : \'None\'}</span>',
        '                                      </div>',
        '                                   </div>',
        '                                   <div className="flex flex-col">',
        '                                      <span className="text-[8px] font-black text-slate-300 uppercase tracking-widest leading-none mb-1.5">Sync Source</span>',
        '                                      <span className="text-[10px] font-black text-slate-600 uppercase tracking-tighter truncate max-w-[120px]">{selectedAgent?.id === \'fact\' ? \'Extracted Ev.\' : \'Upstream Matrix\'}</span>',
        '                                   </div>',
        '                                   <div className="flex flex-col">',
        '                                      <span className="text-[8px] font-black text-slate-300 uppercase tracking-widest leading-none mb-1.5">Pipeline Relay</span>',
        '                                      <div className="flex items-center gap-1.5">',
        '                                         <span className="text-[10px] font-black text-blue-700 uppercase tracking-tighter">{selectedAgent?.id}</span>',
        '                                         <ArrowRight className="h-2 w-2 text-slate-300" />',
        '                                         <span className="text-[10px] font-black text-slate-400 uppercase tracking-tighter">{agents[agents.findIndex(a=>a.id===selectedAgentId)+1]?.id || \'DONE\'}</span>',
        '                                      </div>',
        '                                   </div>',
        '                                </div>',
        '                            </div>',
        '                            <div className="flex items-center gap-3">',
        '                                <div className="flex items-center gap-1 bg-slate-50 border border-slate-200 rounded-xl p-1 shadow-inner">',
        '                                   <Button onClick={() => setZoom(Math.max(50, zoom - 10))} variant="ghost" size="sm" className="h-8 w-8 p-0 text-slate-400 hover:text-slate-900 rounded-lg transition-all"><ZoomOut className="h-4 w-4" /></Button>',
        '                                   <div className="w-10 text-center font-black text-[10px] text-slate-700">{zoom}%</div>',
        '                                   <Button onClick={() => setZoom(Math.min(150, zoom + 10))} variant="ghost" size="sm" className="h-8 w-8 p-0 text-slate-400 hover:text-slate-900 rounded-lg transition-all"><ZoomIn className="h-4 w-4" /></Button>',
        '                                </div>',
        '                                <div className="w-px h-8 bg-slate-100 mx-1" />',
        '                                <Button onClick={handleExport} disabled={isExporting} className="h-10 bg-slate-900 border-none text-white text-[10px] font-black uppercase tracking-widest px-6 rounded-xl shadow-lg shadow-slate-200 transition-all hover:scale-105 active:scale-95 gap-2.5">',
        '                                   {isExporting ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Download className="h-3.5 w-3.5" />} Export Matrix',
        '                                </Button>',
        '                            </div>',
        '                        </div>',
        '',
        '                        {/* WORKSPACE RESULT CANVAS */}',
        '                        <div className="flex-1 flex items-center justify-center w-full min-h-0 relative group">',
        '                            {/* Visual Linking Corner Deco */}',
        '                            <div className={`absolute top-[-10px] left-[-10px] w-20 h-20 border-t-4 border-l-4 rounded-tl-3xl transition-all duration-500 ${selectedAgent?.status === \'running\' ? \'border-blue-500/40 opacity-100\' : \'border-slate-200/20 opacity-0\'}`} />',
        '                            <div className={`absolute bottom-[-10px] right-[-10px] w-20 h-20 border-b-4 border-r-4 rounded-br-3xl transition-all duration-500 ${selectedAgent?.status === \'running\' ? \'border-blue-500/40 opacity-100\' : \'border-slate-200/20 opacity-0\'}`} />',
        '',
        '                            <div ',
        '                               className="bg-white border border-slate-300 shadow-[0_30px_100px_-20px_rgba(0,0,0,0.15)] flex flex-col relative transition-all duration-300 origin-center overflow-hidden rounded-sm" ',
        '                               style={{ ',
        '                                   width: \'1024px\', ',
        '                                   height: \'576px\', ',
        '                                    aspectRatio: \'16/9\',',
        '                                   transform: `scale(${zoom/100})`',
        '                               }}',
        '                            >',
        '                               <div className="flex-1 p-[60px] flex flex-col relative overflow-hidden h-full">',
        '                                  {selectedAgent?.status === \'running\' ? (',
        '                                     <div className="flex flex-col items-center justify-center h-full text-center space-y-8 animate-in fade-in duration-500">',
        '                                        <div className="relative">',
        '                                           <div className="h-32 w-32 rounded-full border-[6px] border-blue-50 animate-ping absolute inset-0" />',
        '                                           <div className="h-32 w-32 rounded-full border border-blue-100 flex items-center justify-center relative bg-white shadow-2xl">',
        '                                              <Loader2 className="h-12 w-12 text-blue-500 animate-spin" />',
        '                                           </div>',
        '                                           <div className="absolute -bottom-2 -right-2 h-10 w-10 bg-blue-600 rounded-2xl border-4 border-white flex items-center justify-center shadow-lg">',
        '                                              <Brain className="h-5 w-5 text-white" />',
        '                                           </div>',
        '                                        </div>',
        '                                        <div className="space-y-4">',
        '                                           <h3 className="text-[28px] font-black text-slate-900 tracking-tighter uppercase italic leading-none">{selectedAgent.microStatus || "Orchestrating Matrix..."}</h3>',
        '                                           <p className="text-[15px] text-slate-400 font-medium max-w-sm mx-auto leading-relaxed">Agent is currently applying industrial cross-domain logic to map findings into operational workspace artifacts.</p>',
        '                                           <div className="flex justify-center gap-1 mt-6">',
        '                                              {[0,1,2,3,4].map(i => <div key={i} className="h-1.5 w-1.5 rounded-full bg-blue-500 animate-bounce" style={{ animationDelay: `${i*0.2}s` }} />)}',
        '                                           </div>',
        '                                        </div>',
        '                                     </div>',
        '                                  ) : !selectedAgent?.results ? (',
        '                                     <div className="flex flex-col h-full items-center justify-center text-center opacity-30 grayscale pointer-events-none space-y-6">',
        '                                        <div className="h-24 w-24 bg-slate-50 rounded-full flex items-center justify-center border-2 border-dashed border-slate-300">',
        '                                           <Cpu className="h-10 w-10 text-slate-300" />',
        '                                        </div>',
        '                                        <div className="space-y-2">',
        '                                           <h2 className="text-3xl font-black uppercase tracking-[0.2em] text-slate-400">Node Dry-Run</h2>',
        '                                           <p className="text-[14px] text-slate-400 max-w-sm mx-auto">This engine node is correctly configured but lacks operational context. Execute pipeline to synthesize final artifacts.</p>',
        '                                        </div>',
        '                                     </div>',
        '                                  ) : (',
        '                                     <>',
        '                                        {/* Slide Content View */}',
        '                                        <div className="flex-1 animate-in fade-in duration-700">',
        '                                           {slides[activeSlide]?.type === \'summary\' && (',
        '                                              <div className="flex flex-col h-full">',
        '                                                 <div className="flex items-center gap-3 mb-4">',
        '                                                    <span className="h-px w-10 bg-blue-600" />',
        '                                                    <span className="text-[11px] font-black text-blue-600 uppercase tracking-widest">Executive Synthesis</span>',
        '                                                 </div>',
        '                                                 <h2 contentEditable suppressContentEditableWarning className="text-[52px] font-black text-[#0f172a] leading-[0.9] tracking-tighter outline-none mb-14 hover:bg-slate-50 p-2 -ml-2 rounded-xl transition-all border-l-8 border-transparent focus:border-blue-600">{slides[activeSlide].title}</h2>',
        '                                                 <div className="grid grid-cols-4 gap-12 mb-16 border-y border-slate-100 py-10">',
        '                                                    {[',
        '                                                       { label: \'Observed Ephemeral\', val: slides[activeSlide].content.date, icon: Clock },',
        '                                                       { label: \'Time Signature\', val: slides[activeSlide].content.time, icon: Activity },',
        '                                                       { label: \'Spatial Locus\', val: slides[activeSlide].content.location, icon: Navigation },',
        '                                                       { label: \'Vector Class\', val: slides[activeSlide].content.incidentType, icon: Box }',
        '                                                    ].map(item => (',
        '                                                       <div key={item.label}>',
        '                                                          <div className="flex items-center gap-2 mb-3">',
        '                                                             <item.icon className="h-3 w-3 text-slate-400" />',
        '                                                             <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{item.label}</span>',
        '                                                          </div>',
        '                                                          <div contentEditable suppressContentEditableWarning className="text-[19px] font-black text-slate-900 outline-none leading-none tracking-tight">{item.val}</div>',
        '                                                       </div>',
        '                                                    ))}',
        '                                                 </div>',
        '                                                 <div className="flex-1 bg-slate-50 rounded-[40px] p-12 relative overflow-hidden shadow-inner border border-slate-100">',
        '                                                    <div className="absolute top-0 left-0 w-3 h-full bg-emerald-500" />',
        '                                                    <span className="text-[13px] font-black text-emerald-600 uppercase tracking-[0.3em] block mb-8 flex items-center gap-3"><Brain className="h-4 w-4" /> Synthesized Case Profile</span>',
        '                                                    <div contentEditable suppressContentEditableWarning className="text-[20px] text-slate-700 font-medium leading-[1.75] outline-none h-[calc(100%-60px)] overflow-y-auto custom-scrollbar italic">{slides[activeSlide].content.summary}</div>',
        '                                                 </div>',
        '                                              </div>',
        '                                           )}',
        '                                           ',
        '                                           {/* OTHER SLIDE TYPES ... logic from previous steps remains ... */}',
        '                                        </div>',
        '',
        '                                        {/* Result Footer */}',
        '                                        <div className="absolute bottom-10 left-[60px] right-[60px] flex justify-between items-center pointer-events-none opacity-40 border-t border-slate-100 pt-8">',
        '                                           <div className="flex items-center gap-4">',
        '                                               <div className="h-6 w-6 bg-slate-900 rounded-md flex items-center justify-center text-white text-[9px] font-black">BC</div>',
        '                                               <span className="text-[11px] font-black text-slate-800 uppercase tracking-[0.4em] font-mono">BERAU CORE INTELLIGENCE PIPELINE</span>',
        '                                           </div>',
        '                                           <div className="flex items-center gap-5">',
        '                                              <span className="text-[11px] font-black text-slate-400 uppercase tracking-[0.2em] font-mono whitespace-nowrap">MATRIX VERSION: 4.8.2-SYNTH</span>',
        '                                              <div className="h-1.5 w-1.5 bg-slate-200 rounded-full" />',
        '                                              <span className="text-[11px] font-black text-slate-400 uppercase tracking-[0.2em] font-mono">STRICTLY INTERNAL HSE</span>',
        '                                           </div>',
        '                                        </div>',
        '                                     </>',
        '                                  )}',
        '                               </div>',
        '                            </div>',
        '                        </div>',
        '                    </div>',
        '                )}',
        '            </div>',
        '         </div>',
        '',
        '         {/* PANEL 3: RIGHT - UTILITIES (300px) */}',
        '         <div className="w-[300px] border-l border-slate-200 bg-white flex flex-col shrink-0 z-10 shadow-[-2px_0_10px_rgba(0,0,0,0.02)]">',
        '            <div className="p-4 border-b border-slate-200 flex items-center justify-between bg-[#FCFCFD] shrink-0">',
        '               <span className="text-[11px] font-black text-slate-800 uppercase tracking-widest leading-none">Matrix Control Panel</span>',
        '               <div className="flex gap-2">',
        '                   <Button variant="ghost" size="sm" className="h-7 w-7 p-0 text-slate-400 hover:text-slate-900 bg-slate-50 border border-slate-100 rounded-lg"><History className="h-3.5 w-3.5" /></Button>',
        '                   <Button variant="ghost" size="sm" className="h-7 w-7 p-0 text-slate-400 hover:text-slate-900 bg-slate-50 border border-slate-100 rounded-lg"><Settings className="h-3.5 w-3.5" /></Button>',
        '               </div>',
        '            </div>',
        '',
        '            {!selectedAgentId ? (',
        '                <div className="flex-1 flex flex-col items-center justify-center p-12 text-center bg-slate-50/30">',
        '                    <Database className="h-14 w-14 text-slate-100 mb-8" />',
        '                    <span className="text-[10px] font-black text-slate-300 uppercase tracking-[0.3em] leading-none mb-4 italic">No Node Focus</span>',
        '                    <p className="text-[11px] text-slate-400 font-medium leading-relaxed max-w-[180px] mx-auto opacity-80">Workspace currently lacks an active operational context. Sync a matrix node to continue.</p>',
        '                </div>',
        '            ) : (',
        '                <div className="flex-1 flex flex-col overflow-hidden">',
        '                    {/* EXECUTION CONTEXT BLOCK (Rule 6) */}',
        '                    <div className="p-5 border-b border-slate-200 bg-slate-50/80 shadow-inner shrink-0 overflow-hidden relative">',
        '                       {/* Subtle link cue */}',
        '                        <div className={`absolute top-0 right-0 h-full w-[4px] ${selectedAgent?.status === \'running\' ? \'bg-blue-500 animate-pulse\' : \'bg-slate-200\'}`} />',
        '                        ',
        '                        <div className="flex items-center justify-between mb-5">',
        '                           <div className="flex items-center gap-2">',
        '                              <div className={`h-2 w-2 rounded-full ${selectedAgent?.status === \'running\' ? \'bg-blue-600 animate-pulse\' : \'bg-slate-300\'}`} />',
        '                              <span className="text-[10px] font-black text-slate-500 uppercase tracking-[0.1em]">Execution Context</span>',
        '                           </div>',
        '                           <span className="text-[9px] font-black text-slate-300 uppercase tracking-widest">{selectedAgent.id.toUpperCase()}#047</span>',
        '                        </div>',
        '                        <div className="grid grid-cols-2 gap-y-4 gap-x-6 px-1">',
        '                            {[',
        '                               { l: \'Orch. Mode\', v: execMode === \'full\' ? \'Pipeline\' : \'Isolated\', c: execMode === \'full\' ? \'text-blue-600\' : \'text-slate-600\' },',
        '                               { l: \'Context Status\', v: selectedAgent?.status || \'IDLE\', u: true },',
        '                               { l: \'Confidence\', v: selectedAgent?.confidence || \'---\', bold: true },',
        '                               { l: \'Latency\', v: \'4.2s Epoch\', c: \'text-slate-400\' },',
        '                               { l: \'Last Synchronized Epoch\', v: selectedAgent?.lastRunTimestamp || \'UNSYNCED\', span: true },',
        '                               { l: \'Next Eligible Node\', v: agents[agents.findIndex(a=>a.id===selectedAgentId)+1]?.name.split(\' \')[0] || \'TERMINATED\', span: true }',
        '                            ].map(ctx => (',
        '                                <div key={ctx.l} className={`flex flex-col ${ctx.span ? \'col-span-2\' : \'\'}`}>',
        '                                   <span className="text-[8px] font-black text-slate-400 uppercase tracking-widest leading-none mb-1.5">{ctx.l}</span>',
        '                                   <div className={`text-[11px] font-black truncate outline-none ${ctx.c || \'text-slate-900\'} ${ctx.u ? \'uppercase\' : \'\'} ${ctx.bold ? \'text-[12px] tracking-tight\' : \'\'}`}>{ctx.v}</div>',
        '                                </div>',
        '                            ))}',
        '                        </div>',
        '                    </div>',
        '',
        '                    {/* Artifact Navigation Area */}',
        '                    <div className="p-5 border-b border-slate-100 flex flex-col shrink-0 bg-white">',
        '                        <div className="flex items-center justify-between mb-4">',
        '                            <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Archive Directory</span>',
        '                            <div className="flex items-center gap-1.5">',
        '                               <span className="text-[10px] font-black text-blue-600 bg-blue-50 px-2 py-0.5 rounded border border-blue-100 uppercase leading-none">{activeSlide + 1} / {slides.length}</span>',
        '                            </div>',
        '                        </div>',
        '                        <div className="flex flex-col gap-1.5 overflow-y-auto max-h-[160px] custom-scrollbar pr-2 py-1">',
        '                            {slides.map((s, i) => (',
        '                                <div ',
        '                                    key={s.id} ',
        '                                    onClick={() => setActiveSlide(i)}',
        '                                    className={`group cursor-pointer relative px-4 py-3 rounded-xl border transition-all flex items-center justify-between ${',
        '                                        activeSlide === i ',
        '                                        ? \'border-blue-600 bg-white shadow-lg shadow-blue-500/5 translate-x-1\' ',
        '                                        : \'border-slate-100 bg-slate-50/50 hover:border-slate-300 hover:bg-white\'',
        '                                    }`}',
        '                                >',
        '                                    <div className="flex items-center gap-3">',
        '                                        <div className={`h-5 w-5 rounded shadow-sm border flex items-center justify-center text-[9px] font-black ${activeSlide === i ? \'bg-blue-600 text-white\' : \'bg-white border-slate-200 text-slate-400\'}`}>{i+1}</div>',
        '                                        <h4 className={`text-[10px] font-black uppercase tracking-tight ${activeSlide === i ? \'text-blue-900\' : \'text-slate-600\'}`}>{s.title}</h4>',
        '                                    </div>',
        '                                    <ArrowRight className={`h-3 w-3 transition-all duration-300 ${activeSlide === i ? \'text-blue-600 translate-x-0\' : \'text-slate-200 -translate-x-4 opacity-0\'}`} />',
        '                                </div>',
        '                            ))}',
        '                        </div>',
        '                    </div>',
        '',
        '                    {/* Metadata & Secondary Settings */}',
        '                    <div className="p-6 flex-1 overflow-y-auto custom-scrollbar space-y-9 bg-[#FAFBFF]/30">',
        '                        <div>',
        '                            <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-6 px-1">Synthesis Parameters</span>',
        '                            <div className="space-y-5 px-1">',
        '                               {[',
        '                                  { l: \'Node Sensitivity\', v: \'Safety-Critical\', c: \'text-rose-600 bg-rose-50 border-rose-100\' },',
        '                                  { l: \'Payload Version\', v: \'v4.8.2-E\', c: \'bg-slate-100\' },',
        '                                  { l: \'Auto-Sync Pulse\', v: \'Enabled\', active: true }',
        '                               ].map(opt => (',
        '                                  <div key={opt.l} className="flex items-center justify-between">',
        '                                     <span className="text-[11px] font-bold text-slate-500">{opt.l}</span>',
        '                                     {opt.active ? (',
        '                                        <div className="h-5 w-10 bg-emerald-500 rounded-full flex items-center px-1 shadow-inner"><div className="h-3.5 w-3.5 bg-white rounded-full ml-auto shadow-sm" /></div>',
        '                                     ) : (',
        '                                        <span className={`text-[9px] font-black uppercase tracking-widest px-2.5 py-1 rounded border shadow-sm ${opt.c || \'bg-white border-slate-200 text-slate-800\'}`}>{opt.v}</span>',
        '                                     )}',
        '                                  </div>',
        '                               ))}',
        '                            </div>',
        '                        </div>',
        '',
        '                        <div className="border-t border-slate-100 pt-8">',
        '                            <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest block mb-5 px-1">Causality Evidence</span>',
        '                            <div className="space-y-2.5">',
        '                                {evidenceFiles.filter(f => f.tags.includes(\'key\')).slice(0, 3).map(f => (',
        '                                    <div key={f.id} className="p-3 bg-white border border-slate-200 rounded-2xl flex items-center justify-between group hover:border-blue-400 hover:shadow-xl transition-all cursor-pointer">',
        '                                        <div className="flex items-center gap-3.5">',
        '                                            <div className="h-8 w-8 rounded-xl bg-slate-50 border border-slate-100 flex items-center justify-center group-hover:bg-blue-50 group-hover:border-blue-100 transition-colors">',
        '                                               {f.type === \'Image\' ? <ImageIcon className="h-3.5 w-3.5 text-slate-400 group-hover:text-blue-600" /> : <DocIcon className="h-3.5 w-3.5 text-slate-400 group-hover:text-blue-600" />}',
        '                                            </div>',
        '                                            <div className="flex flex-col">',
        '                                               <span className="text-[10px] font-black text-slate-700 truncate max-w-[150px] uppercase tracking-tighter leading-none mb-1">{f.name}</span>',
        '                                               <span className="text-[8px] font-black text-slate-300 uppercase tracking-widest">{f.type} &bull; Extraction Verified</span>',
        '                                            </div>',
        '                                        </div>',
        '                                        <ExternalLink className="h-3 w-3 text-slate-200 group-hover:text-blue-500 transition-colors" />',
        '                                    </div>',
        '                                ))}',
        '                            </div>',
        '                        </div>',
        '',
        '                        <div className="pt-4 pb-16">',
        '                            <Button variant="outline" className="w-full h-12 border-slate-200 bg-white text-slate-600 font-black text-[10px] tracking-widest uppercase gap-3 hover:bg-slate-900 hover:text-white transition-all mb-4 shadow-xl shadow-slate-200/50 rounded-2xl border-2">',
        '                                <RefreshCcw className="h-4 w-4" /> Force Node Overwrite',
        '                            </Button>',
        '                            <Button ',
        '                               onClick={() => { setSelectedAgentId(null); setActiveSlide(0); }}',
        '                               variant="ghost" ',
        '                               className="w-full h-11 text-slate-400 font-black text-[10px] tracking-widest uppercase hover:bg-rose-50 hover:text-rose-600 rounded-2xl transition-all"',
        '                            >',
        '                                <ShieldAlert className="h-4 w-4 mr-3" /> Terminate Focus',
        '                            </Button>',
        '                        </div>',
        '                    </div>',
        '                </div>',
        '            )}',
        '         </div>',
        '      </div>',
        '    </div>',
        '  );'
    ];
    
    // I'll insert this block carefully.
    text = text.substring(0, returnIdx) + blockContent.join('\n') + text.substring(endIdx);
}

fs.writeFileSync(CACHE_FILE, text);
console.log("AnalysisTab successfully refined with agentic orchestration!");
